export { default as ProtectedComponent } from "./components/protected-component"
export * from "./models/permissionsProvider"
export * from "./models/permissionsProvider"
export * from "./models/isAuthorizedFn"
export * from "./lib/query-keys"