/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainmodulesRouteRouteImport } from './routes/(main)/(modules)/route'
import { Route as mainResetPasswordIndexRouteImport } from './routes/(main)/reset-password/index'
import { Route as mainmodulesTransactionsIndexRouteImport } from './routes/(main)/(modules)/transactions/index'
import { Route as mainmodulesProjectsIndexRouteImport } from './routes/(main)/(modules)/projects/index'
import { Route as mainmodulesProfilesIndexRouteImport } from './routes/(main)/(modules)/profiles/index'
import { Route as mainmodulesLoansIndexRouteImport } from './routes/(main)/(modules)/loans/index'
import { Route as mainmodulesFollowUpsIndexRouteImport } from './routes/(main)/(modules)/follow-ups/index'
import { Route as mainmodulesCollateralsIndexRouteImport } from './routes/(main)/(modules)/collaterals/index'
import { Route as mainmodulesAmortizationsIndexRouteImport } from './routes/(main)/(modules)/amortizations/index'
import { Route as mainmodulesAdjustmentNotesIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/index'
import { Route as mainmodulesAccountStatementsIndexRouteImport } from './routes/(main)/(modules)/account-statements/index'
import { Route as mainmodulesAccessControlIndexRouteImport } from './routes/(main)/(modules)/access-control/index'
import { Route as mainmodulesTransactionsReportsIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/index'
import { Route as mainmodulesTransactionsPeriodsIndexRouteImport } from './routes/(main)/(modules)/transactions/periods/index'
import { Route as mainmodulesTransactionsCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/create/index'
import { Route as mainmodulesTransactionsIdIndexRouteImport } from './routes/(main)/(modules)/transactions/$id/index'
import { Route as mainmodulesProjectsSettingsIndexRouteImport } from './routes/(main)/(modules)/projects/settings/index'
import { Route as mainmodulesProjectsCreateIndexRouteImport } from './routes/(main)/(modules)/projects/create/index'
import { Route as mainmodulesProfilesCreateIndexRouteImport } from './routes/(main)/(modules)/profiles/create/index'
import { Route as mainmodulesProfilesIdIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/index'
import { Route as mainmodulesLoansReportsIndexRouteImport } from './routes/(main)/(modules)/loans/reports/index'
import { Route as mainmodulesLoansPurposesIndexRouteImport } from './routes/(main)/(modules)/loans/purposes/index'
import { Route as mainmodulesLoansCreateIndexRouteImport } from './routes/(main)/(modules)/loans/create/index'
import { Route as mainmodulesLoansIdIndexRouteImport } from './routes/(main)/(modules)/loans/$id/index'
import { Route as mainmodulesFollowUpsCreateIndexRouteImport } from './routes/(main)/(modules)/follow-ups/create/index'
import { Route as mainmodulesFollowUpsIdIndexRouteImport } from './routes/(main)/(modules)/follow-ups/$id/index'
import { Route as mainmodulesFinanceProjectionsIndexRouteImport } from './routes/(main)/(modules)/finance/projections/index'
import { Route as mainmodulesFinanceIncomesIndexRouteImport } from './routes/(main)/(modules)/finance/incomes/index'
import { Route as mainmodulesFinanceExpensesIndexRouteImport } from './routes/(main)/(modules)/finance/expenses/index'
import { Route as mainmodulesCollateralsReportsIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/index'
import { Route as mainmodulesCollateralsCreateIndexRouteImport } from './routes/(main)/(modules)/collaterals/create/index'
import { Route as mainmodulesCollateralsIdIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/index'
import { Route as mainmodulesAdjustmentNotesCreateIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/create/index'
import { Route as mainmodulesAdjustmentNotesIdIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/$id/index'
import { Route as mainmodulesTransactionsReportsGenerateIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/generate/index'
import { Route as mainmodulesTransactionsReportsCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/create/index'
import { Route as mainmodulesTransactionsReportsIdIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/$id/index'
import { Route as mainmodulesTransactionsPeriodsCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/periods/create/index'
import { Route as mainmodulesTransactionsIdDeleteIndexRouteImport } from './routes/(main)/(modules)/transactions/$id/delete/index'
import { Route as mainmodulesProfilesIdEditIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/edit/index'
import { Route as mainmodulesProfilesIdDeleteIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/delete/index'
import { Route as mainmodulesProfilesIdChangesIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/changes/index'
import { Route as mainmodulesLoansReportsGenerateIndexRouteImport } from './routes/(main)/(modules)/loans/reports/generate/index'
import { Route as mainmodulesLoansReportsCreateIndexRouteImport } from './routes/(main)/(modules)/loans/reports/create/index'
import { Route as mainmodulesLoansReportsIdIndexRouteImport } from './routes/(main)/(modules)/loans/reports/$id/index'
import { Route as mainmodulesLoansPurposesCreateIndexRouteImport } from './routes/(main)/(modules)/loans/purposes/create/index'
import { Route as mainmodulesLoansIdSettingsIndexRouteImport } from './routes/(main)/(modules)/loans/$id/settings/index'
import { Route as mainmodulesLoansIdDeleteIndexRouteImport } from './routes/(main)/(modules)/loans/$id/delete/index'
import { Route as mainmodulesLoansIdChangesIndexRouteImport } from './routes/(main)/(modules)/loans/$id/changes/index'
import { Route as mainmodulesFollowUpsIdEditIndexRouteImport } from './routes/(main)/(modules)/follow-ups/$id/edit/index'
import { Route as mainmodulesCollateralsReportsGenerateIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/generate/index'
import { Route as mainmodulesCollateralsReportsCreateIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/create/index'
import { Route as mainmodulesCollateralsReportsIdIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/$id/index'
import { Route as mainmodulesCollateralsIdSettingsIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/settings/index'
import { Route as mainmodulesCollateralsIdEditIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/edit/index'
import { Route as mainmodulesCollateralsIdDeleteIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/delete/index'
import { Route as mainmodulesCollateralsIdChangesIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/changes/index'
import { Route as mainmodulesAdjustmentNotesIdDeleteIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/$id/delete/index'
import { Route as mainmodulesAccessControlUsersCreateIndexRouteImport } from './routes/(main)/(modules)/access-control/users/create/index'
import { Route as mainmodulesAccessControlUsersUsernameIndexRouteImport } from './routes/(main)/(modules)/access-control/users/$username/index'
import { Route as mainmodulesAccessControlRolesCreateIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/create/index'
import { Route as mainmodulesAccessControlRolesIdIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/index'
import { Route as mainmodulesTransactionsReportsReceiptCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/receipt/create/index'
import { Route as mainmodulesTransactionsReportsIdEditIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/$id/edit/index'
import { Route as mainmodulesTransactionsReportsIdDeleteIndexRouteImport } from './routes/(main)/(modules)/transactions/reports/$id/delete/index'
import { Route as mainmodulesLoansReportsIdEditIndexRouteImport } from './routes/(main)/(modules)/loans/reports/$id/edit/index'
import { Route as mainmodulesLoansReportsIdDeleteIndexRouteImport } from './routes/(main)/(modules)/loans/reports/$id/delete/index'
import { Route as mainmodulesLoansPurposesIdEditIndexRouteImport } from './routes/(main)/(modules)/loans/purposes/$id/edit/index'
import { Route as mainmodulesCollateralsReportsIdEditIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/$id/edit/index'
import { Route as mainmodulesCollateralsReportsIdDeleteIndexRouteImport } from './routes/(main)/(modules)/collaterals/reports/$id/delete/index'
import { Route as mainmodulesAccessControlUsersUsernameEditIndexRouteImport } from './routes/(main)/(modules)/access-control/users/$username/edit/index'
import { Route as mainmodulesAccessControlUsersUsernameChangesIndexRouteImport } from './routes/(main)/(modules)/access-control/users/$username/changes/index'
import { Route as mainmodulesAccessControlRolesIdEditIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/edit/index'
import { Route as mainmodulesAccessControlRolesIdDeleteIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/delete/index'
import { Route as mainmodulesAccessControlRolesIdChangesIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/changes/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainmodulesRouteRoute = mainmodulesRouteRouteImport.update({
  id: '/(modules)',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainResetPasswordIndexRoute = mainResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainmodulesTransactionsIndexRoute =
  mainmodulesTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProjectsIndexRoute =
  mainmodulesProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIndexRoute =
  mainmodulesProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIndexRoute = mainmodulesLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => mainmodulesRouteRoute,
} as any)
const mainmodulesFollowUpsIndexRoute =
  mainmodulesFollowUpsIndexRouteImport.update({
    id: '/follow-ups/',
    path: '/follow-ups/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIndexRoute =
  mainmodulesCollateralsIndexRouteImport.update({
    id: '/collaterals/',
    path: '/collaterals/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAmortizationsIndexRoute =
  mainmodulesAmortizationsIndexRouteImport.update({
    id: '/amortizations/',
    path: '/amortizations/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesIndexRoute =
  mainmodulesAdjustmentNotesIndexRouteImport.update({
    id: '/adjustment-notes/',
    path: '/adjustment-notes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccountStatementsIndexRoute =
  mainmodulesAccountStatementsIndexRouteImport.update({
    id: '/account-statements/',
    path: '/account-statements/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlIndexRoute =
  mainmodulesAccessControlIndexRouteImport.update({
    id: '/access-control/',
    path: '/access-control/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsIndexRoute =
  mainmodulesTransactionsReportsIndexRouteImport.update({
    id: '/transactions/reports/',
    path: '/transactions/reports/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsPeriodsIndexRoute =
  mainmodulesTransactionsPeriodsIndexRouteImport.update({
    id: '/transactions/periods/',
    path: '/transactions/periods/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsCreateIndexRoute =
  mainmodulesTransactionsCreateIndexRouteImport.update({
    id: '/transactions/create/',
    path: '/transactions/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsIdIndexRoute =
  mainmodulesTransactionsIdIndexRouteImport.update({
    id: '/transactions/$id/',
    path: '/transactions/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProjectsSettingsIndexRoute =
  mainmodulesProjectsSettingsIndexRouteImport.update({
    id: '/projects/settings/',
    path: '/projects/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProjectsCreateIndexRoute =
  mainmodulesProjectsCreateIndexRouteImport.update({
    id: '/projects/create/',
    path: '/projects/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesCreateIndexRoute =
  mainmodulesProfilesCreateIndexRouteImport.update({
    id: '/profiles/create/',
    path: '/profiles/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdIndexRoute =
  mainmodulesProfilesIdIndexRouteImport.update({
    id: '/profiles/$id/',
    path: '/profiles/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsIndexRoute =
  mainmodulesLoansReportsIndexRouteImport.update({
    id: '/loans/reports/',
    path: '/loans/reports/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurposesIndexRoute =
  mainmodulesLoansPurposesIndexRouteImport.update({
    id: '/loans/purposes/',
    path: '/loans/purposes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansCreateIndexRoute =
  mainmodulesLoansCreateIndexRouteImport.update({
    id: '/loans/create/',
    path: '/loans/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdIndexRoute = mainmodulesLoansIdIndexRouteImport.update({
  id: '/loans/$id/',
  path: '/loans/$id/',
  getParentRoute: () => mainmodulesRouteRoute,
} as any)
const mainmodulesFollowUpsCreateIndexRoute =
  mainmodulesFollowUpsCreateIndexRouteImport.update({
    id: '/follow-ups/create/',
    path: '/follow-ups/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFollowUpsIdIndexRoute =
  mainmodulesFollowUpsIdIndexRouteImport.update({
    id: '/follow-ups/$id/',
    path: '/follow-ups/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceProjectionsIndexRoute =
  mainmodulesFinanceProjectionsIndexRouteImport.update({
    id: '/finance/projections/',
    path: '/finance/projections/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceIncomesIndexRoute =
  mainmodulesFinanceIncomesIndexRouteImport.update({
    id: '/finance/incomes/',
    path: '/finance/incomes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceExpensesIndexRoute =
  mainmodulesFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsIndexRoute =
  mainmodulesCollateralsReportsIndexRouteImport.update({
    id: '/collaterals/reports/',
    path: '/collaterals/reports/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsCreateIndexRoute =
  mainmodulesCollateralsCreateIndexRouteImport.update({
    id: '/collaterals/create/',
    path: '/collaterals/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdIndexRoute =
  mainmodulesCollateralsIdIndexRouteImport.update({
    id: '/collaterals/$id/',
    path: '/collaterals/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesCreateIndexRoute =
  mainmodulesAdjustmentNotesCreateIndexRouteImport.update({
    id: '/adjustment-notes/create/',
    path: '/adjustment-notes/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesIdIndexRoute =
  mainmodulesAdjustmentNotesIdIndexRouteImport.update({
    id: '/adjustment-notes/$id/',
    path: '/adjustment-notes/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsGenerateIndexRoute =
  mainmodulesTransactionsReportsGenerateIndexRouteImport.update({
    id: '/transactions/reports/generate/',
    path: '/transactions/reports/generate/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsCreateIndexRoute =
  mainmodulesTransactionsReportsCreateIndexRouteImport.update({
    id: '/transactions/reports/create/',
    path: '/transactions/reports/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsIdIndexRoute =
  mainmodulesTransactionsReportsIdIndexRouteImport.update({
    id: '/transactions/reports/$id/',
    path: '/transactions/reports/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsPeriodsCreateIndexRoute =
  mainmodulesTransactionsPeriodsCreateIndexRouteImport.update({
    id: '/transactions/periods/create/',
    path: '/transactions/periods/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsIdDeleteIndexRoute =
  mainmodulesTransactionsIdDeleteIndexRouteImport.update({
    id: '/transactions/$id/delete/',
    path: '/transactions/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdEditIndexRoute =
  mainmodulesProfilesIdEditIndexRouteImport.update({
    id: '/profiles/$id/edit/',
    path: '/profiles/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdDeleteIndexRoute =
  mainmodulesProfilesIdDeleteIndexRouteImport.update({
    id: '/profiles/$id/delete/',
    path: '/profiles/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdChangesIndexRoute =
  mainmodulesProfilesIdChangesIndexRouteImport.update({
    id: '/profiles/$id/changes/',
    path: '/profiles/$id/changes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsGenerateIndexRoute =
  mainmodulesLoansReportsGenerateIndexRouteImport.update({
    id: '/loans/reports/generate/',
    path: '/loans/reports/generate/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsCreateIndexRoute =
  mainmodulesLoansReportsCreateIndexRouteImport.update({
    id: '/loans/reports/create/',
    path: '/loans/reports/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsIdIndexRoute =
  mainmodulesLoansReportsIdIndexRouteImport.update({
    id: '/loans/reports/$id/',
    path: '/loans/reports/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurposesCreateIndexRoute =
  mainmodulesLoansPurposesCreateIndexRouteImport.update({
    id: '/loans/purposes/create/',
    path: '/loans/purposes/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdSettingsIndexRoute =
  mainmodulesLoansIdSettingsIndexRouteImport.update({
    id: '/loans/$id/settings/',
    path: '/loans/$id/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdDeleteIndexRoute =
  mainmodulesLoansIdDeleteIndexRouteImport.update({
    id: '/loans/$id/delete/',
    path: '/loans/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdChangesIndexRoute =
  mainmodulesLoansIdChangesIndexRouteImport.update({
    id: '/loans/$id/changes/',
    path: '/loans/$id/changes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFollowUpsIdEditIndexRoute =
  mainmodulesFollowUpsIdEditIndexRouteImport.update({
    id: '/follow-ups/$id/edit/',
    path: '/follow-ups/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsGenerateIndexRoute =
  mainmodulesCollateralsReportsGenerateIndexRouteImport.update({
    id: '/collaterals/reports/generate/',
    path: '/collaterals/reports/generate/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsCreateIndexRoute =
  mainmodulesCollateralsReportsCreateIndexRouteImport.update({
    id: '/collaterals/reports/create/',
    path: '/collaterals/reports/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsIdIndexRoute =
  mainmodulesCollateralsReportsIdIndexRouteImport.update({
    id: '/collaterals/reports/$id/',
    path: '/collaterals/reports/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdSettingsIndexRoute =
  mainmodulesCollateralsIdSettingsIndexRouteImport.update({
    id: '/collaterals/$id/settings/',
    path: '/collaterals/$id/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdEditIndexRoute =
  mainmodulesCollateralsIdEditIndexRouteImport.update({
    id: '/collaterals/$id/edit/',
    path: '/collaterals/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdDeleteIndexRoute =
  mainmodulesCollateralsIdDeleteIndexRouteImport.update({
    id: '/collaterals/$id/delete/',
    path: '/collaterals/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdChangesIndexRoute =
  mainmodulesCollateralsIdChangesIndexRouteImport.update({
    id: '/collaterals/$id/changes/',
    path: '/collaterals/$id/changes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesIdDeleteIndexRoute =
  mainmodulesAdjustmentNotesIdDeleteIndexRouteImport.update({
    id: '/adjustment-notes/$id/delete/',
    path: '/adjustment-notes/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersCreateIndexRoute =
  mainmodulesAccessControlUsersCreateIndexRouteImport.update({
    id: '/access-control/users/create/',
    path: '/access-control/users/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersUsernameIndexRoute =
  mainmodulesAccessControlUsersUsernameIndexRouteImport.update({
    id: '/access-control/users/$username/',
    path: '/access-control/users/$username/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesCreateIndexRoute =
  mainmodulesAccessControlRolesCreateIndexRouteImport.update({
    id: '/access-control/roles/create/',
    path: '/access-control/roles/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdIndexRoute =
  mainmodulesAccessControlRolesIdIndexRouteImport.update({
    id: '/access-control/roles/$id/',
    path: '/access-control/roles/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsReceiptCreateIndexRoute =
  mainmodulesTransactionsReportsReceiptCreateIndexRouteImport.update({
    id: '/transactions/reports/receipt/create/',
    path: '/transactions/reports/receipt/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsIdEditIndexRoute =
  mainmodulesTransactionsReportsIdEditIndexRouteImport.update({
    id: '/transactions/reports/$id/edit/',
    path: '/transactions/reports/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReportsIdDeleteIndexRoute =
  mainmodulesTransactionsReportsIdDeleteIndexRouteImport.update({
    id: '/transactions/reports/$id/delete/',
    path: '/transactions/reports/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsIdEditIndexRoute =
  mainmodulesLoansReportsIdEditIndexRouteImport.update({
    id: '/loans/reports/$id/edit/',
    path: '/loans/reports/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansReportsIdDeleteIndexRoute =
  mainmodulesLoansReportsIdDeleteIndexRouteImport.update({
    id: '/loans/reports/$id/delete/',
    path: '/loans/reports/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurposesIdEditIndexRoute =
  mainmodulesLoansPurposesIdEditIndexRouteImport.update({
    id: '/loans/purposes/$id/edit/',
    path: '/loans/purposes/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsIdEditIndexRoute =
  mainmodulesCollateralsReportsIdEditIndexRouteImport.update({
    id: '/collaterals/reports/$id/edit/',
    path: '/collaterals/reports/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsReportsIdDeleteIndexRoute =
  mainmodulesCollateralsReportsIdDeleteIndexRouteImport.update({
    id: '/collaterals/reports/$id/delete/',
    path: '/collaterals/reports/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersUsernameEditIndexRoute =
  mainmodulesAccessControlUsersUsernameEditIndexRouteImport.update({
    id: '/access-control/users/$username/edit/',
    path: '/access-control/users/$username/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersUsernameChangesIndexRoute =
  mainmodulesAccessControlUsersUsernameChangesIndexRouteImport.update({
    id: '/access-control/users/$username/changes/',
    path: '/access-control/users/$username/changes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdEditIndexRoute =
  mainmodulesAccessControlRolesIdEditIndexRouteImport.update({
    id: '/access-control/roles/$id/edit/',
    path: '/access-control/roles/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdDeleteIndexRoute =
  mainmodulesAccessControlRolesIdDeleteIndexRouteImport.update({
    id: '/access-control/roles/$id/delete/',
    path: '/access-control/roles/$id/delete/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdChangesIndexRoute =
  mainmodulesAccessControlRolesIdChangesIndexRouteImport.update({
    id: '/access-control/roles/$id/changes/',
    path: '/access-control/roles/$id/changes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/reset-password/': typeof mainResetPasswordIndexRoute
  '/access-control/': typeof mainmodulesAccessControlIndexRoute
  '/account-statements/': typeof mainmodulesAccountStatementsIndexRoute
  '/adjustment-notes/': typeof mainmodulesAdjustmentNotesIndexRoute
  '/amortizations/': typeof mainmodulesAmortizationsIndexRoute
  '/collaterals/': typeof mainmodulesCollateralsIndexRoute
  '/follow-ups/': typeof mainmodulesFollowUpsIndexRoute
  '/loans/': typeof mainmodulesLoansIndexRoute
  '/profiles/': typeof mainmodulesProfilesIndexRoute
  '/projects/': typeof mainmodulesProjectsIndexRoute
  '/transactions/': typeof mainmodulesTransactionsIndexRoute
  '/adjustment-notes/$id/': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/adjustment-notes/create/': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/collaterals/$id/': typeof mainmodulesCollateralsIdIndexRoute
  '/collaterals/create/': typeof mainmodulesCollateralsCreateIndexRoute
  '/collaterals/reports/': typeof mainmodulesCollateralsReportsIndexRoute
  '/finance/expenses/': typeof mainmodulesFinanceExpensesIndexRoute
  '/finance/incomes/': typeof mainmodulesFinanceIncomesIndexRoute
  '/finance/projections/': typeof mainmodulesFinanceProjectionsIndexRoute
  '/follow-ups/$id/': typeof mainmodulesFollowUpsIdIndexRoute
  '/follow-ups/create/': typeof mainmodulesFollowUpsCreateIndexRoute
  '/loans/$id/': typeof mainmodulesLoansIdIndexRoute
  '/loans/create/': typeof mainmodulesLoansCreateIndexRoute
  '/loans/purposes/': typeof mainmodulesLoansPurposesIndexRoute
  '/loans/reports/': typeof mainmodulesLoansReportsIndexRoute
  '/profiles/$id/': typeof mainmodulesProfilesIdIndexRoute
  '/profiles/create/': typeof mainmodulesProfilesCreateIndexRoute
  '/projects/create/': typeof mainmodulesProjectsCreateIndexRoute
  '/projects/settings/': typeof mainmodulesProjectsSettingsIndexRoute
  '/transactions/$id/': typeof mainmodulesTransactionsIdIndexRoute
  '/transactions/create/': typeof mainmodulesTransactionsCreateIndexRoute
  '/transactions/periods/': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/transactions/reports/': typeof mainmodulesTransactionsReportsIndexRoute
  '/access-control/roles/$id/': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/access-control/roles/create/': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/access-control/users/$username/': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/access-control/users/create/': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/adjustment-notes/$id/delete/': typeof mainmodulesAdjustmentNotesIdDeleteIndexRoute
  '/collaterals/$id/changes/': typeof mainmodulesCollateralsIdChangesIndexRoute
  '/collaterals/$id/delete/': typeof mainmodulesCollateralsIdDeleteIndexRoute
  '/collaterals/$id/edit/': typeof mainmodulesCollateralsIdEditIndexRoute
  '/collaterals/$id/settings/': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/collaterals/reports/$id/': typeof mainmodulesCollateralsReportsIdIndexRoute
  '/collaterals/reports/create/': typeof mainmodulesCollateralsReportsCreateIndexRoute
  '/collaterals/reports/generate/': typeof mainmodulesCollateralsReportsGenerateIndexRoute
  '/follow-ups/$id/edit/': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/loans/$id/changes/': typeof mainmodulesLoansIdChangesIndexRoute
  '/loans/$id/delete/': typeof mainmodulesLoansIdDeleteIndexRoute
  '/loans/$id/settings/': typeof mainmodulesLoansIdSettingsIndexRoute
  '/loans/purposes/create/': typeof mainmodulesLoansPurposesCreateIndexRoute
  '/loans/reports/$id/': typeof mainmodulesLoansReportsIdIndexRoute
  '/loans/reports/create/': typeof mainmodulesLoansReportsCreateIndexRoute
  '/loans/reports/generate/': typeof mainmodulesLoansReportsGenerateIndexRoute
  '/profiles/$id/changes/': typeof mainmodulesProfilesIdChangesIndexRoute
  '/profiles/$id/delete/': typeof mainmodulesProfilesIdDeleteIndexRoute
  '/profiles/$id/edit/': typeof mainmodulesProfilesIdEditIndexRoute
  '/transactions/$id/delete/': typeof mainmodulesTransactionsIdDeleteIndexRoute
  '/transactions/periods/create/': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/transactions/reports/$id/': typeof mainmodulesTransactionsReportsIdIndexRoute
  '/transactions/reports/create/': typeof mainmodulesTransactionsReportsCreateIndexRoute
  '/transactions/reports/generate/': typeof mainmodulesTransactionsReportsGenerateIndexRoute
  '/access-control/roles/$id/changes/': typeof mainmodulesAccessControlRolesIdChangesIndexRoute
  '/access-control/roles/$id/delete/': typeof mainmodulesAccessControlRolesIdDeleteIndexRoute
  '/access-control/roles/$id/edit/': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/access-control/users/$username/changes/': typeof mainmodulesAccessControlUsersUsernameChangesIndexRoute
  '/access-control/users/$username/edit/': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/collaterals/reports/$id/delete/': typeof mainmodulesCollateralsReportsIdDeleteIndexRoute
  '/collaterals/reports/$id/edit/': typeof mainmodulesCollateralsReportsIdEditIndexRoute
  '/loans/purposes/$id/edit/': typeof mainmodulesLoansPurposesIdEditIndexRoute
  '/loans/reports/$id/delete/': typeof mainmodulesLoansReportsIdDeleteIndexRoute
  '/loans/reports/$id/edit/': typeof mainmodulesLoansReportsIdEditIndexRoute
  '/transactions/reports/$id/delete/': typeof mainmodulesTransactionsReportsIdDeleteIndexRoute
  '/transactions/reports/$id/edit/': typeof mainmodulesTransactionsReportsIdEditIndexRoute
  '/transactions/reports/receipt/create/': typeof mainmodulesTransactionsReportsReceiptCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/reset-password': typeof mainResetPasswordIndexRoute
  '/access-control': typeof mainmodulesAccessControlIndexRoute
  '/account-statements': typeof mainmodulesAccountStatementsIndexRoute
  '/adjustment-notes': typeof mainmodulesAdjustmentNotesIndexRoute
  '/amortizations': typeof mainmodulesAmortizationsIndexRoute
  '/collaterals': typeof mainmodulesCollateralsIndexRoute
  '/follow-ups': typeof mainmodulesFollowUpsIndexRoute
  '/loans': typeof mainmodulesLoansIndexRoute
  '/profiles': typeof mainmodulesProfilesIndexRoute
  '/projects': typeof mainmodulesProjectsIndexRoute
  '/transactions': typeof mainmodulesTransactionsIndexRoute
  '/adjustment-notes/$id': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/adjustment-notes/create': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/collaterals/$id': typeof mainmodulesCollateralsIdIndexRoute
  '/collaterals/create': typeof mainmodulesCollateralsCreateIndexRoute
  '/collaterals/reports': typeof mainmodulesCollateralsReportsIndexRoute
  '/finance/expenses': typeof mainmodulesFinanceExpensesIndexRoute
  '/finance/incomes': typeof mainmodulesFinanceIncomesIndexRoute
  '/finance/projections': typeof mainmodulesFinanceProjectionsIndexRoute
  '/follow-ups/$id': typeof mainmodulesFollowUpsIdIndexRoute
  '/follow-ups/create': typeof mainmodulesFollowUpsCreateIndexRoute
  '/loans/$id': typeof mainmodulesLoansIdIndexRoute
  '/loans/create': typeof mainmodulesLoansCreateIndexRoute
  '/loans/purposes': typeof mainmodulesLoansPurposesIndexRoute
  '/loans/reports': typeof mainmodulesLoansReportsIndexRoute
  '/profiles/$id': typeof mainmodulesProfilesIdIndexRoute
  '/profiles/create': typeof mainmodulesProfilesCreateIndexRoute
  '/projects/create': typeof mainmodulesProjectsCreateIndexRoute
  '/projects/settings': typeof mainmodulesProjectsSettingsIndexRoute
  '/transactions/$id': typeof mainmodulesTransactionsIdIndexRoute
  '/transactions/create': typeof mainmodulesTransactionsCreateIndexRoute
  '/transactions/periods': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/transactions/reports': typeof mainmodulesTransactionsReportsIndexRoute
  '/access-control/roles/$id': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/access-control/roles/create': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/access-control/users/$username': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/access-control/users/create': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/adjustment-notes/$id/delete': typeof mainmodulesAdjustmentNotesIdDeleteIndexRoute
  '/collaterals/$id/changes': typeof mainmodulesCollateralsIdChangesIndexRoute
  '/collaterals/$id/delete': typeof mainmodulesCollateralsIdDeleteIndexRoute
  '/collaterals/$id/edit': typeof mainmodulesCollateralsIdEditIndexRoute
  '/collaterals/$id/settings': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/collaterals/reports/$id': typeof mainmodulesCollateralsReportsIdIndexRoute
  '/collaterals/reports/create': typeof mainmodulesCollateralsReportsCreateIndexRoute
  '/collaterals/reports/generate': typeof mainmodulesCollateralsReportsGenerateIndexRoute
  '/follow-ups/$id/edit': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/loans/$id/changes': typeof mainmodulesLoansIdChangesIndexRoute
  '/loans/$id/delete': typeof mainmodulesLoansIdDeleteIndexRoute
  '/loans/$id/settings': typeof mainmodulesLoansIdSettingsIndexRoute
  '/loans/purposes/create': typeof mainmodulesLoansPurposesCreateIndexRoute
  '/loans/reports/$id': typeof mainmodulesLoansReportsIdIndexRoute
  '/loans/reports/create': typeof mainmodulesLoansReportsCreateIndexRoute
  '/loans/reports/generate': typeof mainmodulesLoansReportsGenerateIndexRoute
  '/profiles/$id/changes': typeof mainmodulesProfilesIdChangesIndexRoute
  '/profiles/$id/delete': typeof mainmodulesProfilesIdDeleteIndexRoute
  '/profiles/$id/edit': typeof mainmodulesProfilesIdEditIndexRoute
  '/transactions/$id/delete': typeof mainmodulesTransactionsIdDeleteIndexRoute
  '/transactions/periods/create': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/transactions/reports/$id': typeof mainmodulesTransactionsReportsIdIndexRoute
  '/transactions/reports/create': typeof mainmodulesTransactionsReportsCreateIndexRoute
  '/transactions/reports/generate': typeof mainmodulesTransactionsReportsGenerateIndexRoute
  '/access-control/roles/$id/changes': typeof mainmodulesAccessControlRolesIdChangesIndexRoute
  '/access-control/roles/$id/delete': typeof mainmodulesAccessControlRolesIdDeleteIndexRoute
  '/access-control/roles/$id/edit': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/access-control/users/$username/changes': typeof mainmodulesAccessControlUsersUsernameChangesIndexRoute
  '/access-control/users/$username/edit': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/collaterals/reports/$id/delete': typeof mainmodulesCollateralsReportsIdDeleteIndexRoute
  '/collaterals/reports/$id/edit': typeof mainmodulesCollateralsReportsIdEditIndexRoute
  '/loans/purposes/$id/edit': typeof mainmodulesLoansPurposesIdEditIndexRoute
  '/loans/reports/$id/delete': typeof mainmodulesLoansReportsIdDeleteIndexRoute
  '/loans/reports/$id/edit': typeof mainmodulesLoansReportsIdEditIndexRoute
  '/transactions/reports/$id/delete': typeof mainmodulesTransactionsReportsIdDeleteIndexRoute
  '/transactions/reports/$id/edit': typeof mainmodulesTransactionsReportsIdEditIndexRoute
  '/transactions/reports/receipt/create': typeof mainmodulesTransactionsReportsReceiptCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/(modules)': typeof mainmodulesRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/(main)/reset-password/': typeof mainResetPasswordIndexRoute
  '/(main)/(modules)/access-control/': typeof mainmodulesAccessControlIndexRoute
  '/(main)/(modules)/account-statements/': typeof mainmodulesAccountStatementsIndexRoute
  '/(main)/(modules)/adjustment-notes/': typeof mainmodulesAdjustmentNotesIndexRoute
  '/(main)/(modules)/amortizations/': typeof mainmodulesAmortizationsIndexRoute
  '/(main)/(modules)/collaterals/': typeof mainmodulesCollateralsIndexRoute
  '/(main)/(modules)/follow-ups/': typeof mainmodulesFollowUpsIndexRoute
  '/(main)/(modules)/loans/': typeof mainmodulesLoansIndexRoute
  '/(main)/(modules)/profiles/': typeof mainmodulesProfilesIndexRoute
  '/(main)/(modules)/projects/': typeof mainmodulesProjectsIndexRoute
  '/(main)/(modules)/transactions/': typeof mainmodulesTransactionsIndexRoute
  '/(main)/(modules)/adjustment-notes/$id/': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/(main)/(modules)/adjustment-notes/create/': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/(main)/(modules)/collaterals/$id/': typeof mainmodulesCollateralsIdIndexRoute
  '/(main)/(modules)/collaterals/create/': typeof mainmodulesCollateralsCreateIndexRoute
  '/(main)/(modules)/collaterals/reports/': typeof mainmodulesCollateralsReportsIndexRoute
  '/(main)/(modules)/finance/expenses/': typeof mainmodulesFinanceExpensesIndexRoute
  '/(main)/(modules)/finance/incomes/': typeof mainmodulesFinanceIncomesIndexRoute
  '/(main)/(modules)/finance/projections/': typeof mainmodulesFinanceProjectionsIndexRoute
  '/(main)/(modules)/follow-ups/$id/': typeof mainmodulesFollowUpsIdIndexRoute
  '/(main)/(modules)/follow-ups/create/': typeof mainmodulesFollowUpsCreateIndexRoute
  '/(main)/(modules)/loans/$id/': typeof mainmodulesLoansIdIndexRoute
  '/(main)/(modules)/loans/create/': typeof mainmodulesLoansCreateIndexRoute
  '/(main)/(modules)/loans/purposes/': typeof mainmodulesLoansPurposesIndexRoute
  '/(main)/(modules)/loans/reports/': typeof mainmodulesLoansReportsIndexRoute
  '/(main)/(modules)/profiles/$id/': typeof mainmodulesProfilesIdIndexRoute
  '/(main)/(modules)/profiles/create/': typeof mainmodulesProfilesCreateIndexRoute
  '/(main)/(modules)/projects/create/': typeof mainmodulesProjectsCreateIndexRoute
  '/(main)/(modules)/projects/settings/': typeof mainmodulesProjectsSettingsIndexRoute
  '/(main)/(modules)/transactions/$id/': typeof mainmodulesTransactionsIdIndexRoute
  '/(main)/(modules)/transactions/create/': typeof mainmodulesTransactionsCreateIndexRoute
  '/(main)/(modules)/transactions/periods/': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/(main)/(modules)/transactions/reports/': typeof mainmodulesTransactionsReportsIndexRoute
  '/(main)/(modules)/access-control/roles/$id/': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/(main)/(modules)/access-control/roles/create/': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/(main)/(modules)/access-control/users/$username/': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/(main)/(modules)/access-control/users/create/': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/(main)/(modules)/adjustment-notes/$id/delete/': typeof mainmodulesAdjustmentNotesIdDeleteIndexRoute
  '/(main)/(modules)/collaterals/$id/changes/': typeof mainmodulesCollateralsIdChangesIndexRoute
  '/(main)/(modules)/collaterals/$id/delete/': typeof mainmodulesCollateralsIdDeleteIndexRoute
  '/(main)/(modules)/collaterals/$id/edit/': typeof mainmodulesCollateralsIdEditIndexRoute
  '/(main)/(modules)/collaterals/$id/settings/': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/(main)/(modules)/collaterals/reports/$id/': typeof mainmodulesCollateralsReportsIdIndexRoute
  '/(main)/(modules)/collaterals/reports/create/': typeof mainmodulesCollateralsReportsCreateIndexRoute
  '/(main)/(modules)/collaterals/reports/generate/': typeof mainmodulesCollateralsReportsGenerateIndexRoute
  '/(main)/(modules)/follow-ups/$id/edit/': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/(main)/(modules)/loans/$id/changes/': typeof mainmodulesLoansIdChangesIndexRoute
  '/(main)/(modules)/loans/$id/delete/': typeof mainmodulesLoansIdDeleteIndexRoute
  '/(main)/(modules)/loans/$id/settings/': typeof mainmodulesLoansIdSettingsIndexRoute
  '/(main)/(modules)/loans/purposes/create/': typeof mainmodulesLoansPurposesCreateIndexRoute
  '/(main)/(modules)/loans/reports/$id/': typeof mainmodulesLoansReportsIdIndexRoute
  '/(main)/(modules)/loans/reports/create/': typeof mainmodulesLoansReportsCreateIndexRoute
  '/(main)/(modules)/loans/reports/generate/': typeof mainmodulesLoansReportsGenerateIndexRoute
  '/(main)/(modules)/profiles/$id/changes/': typeof mainmodulesProfilesIdChangesIndexRoute
  '/(main)/(modules)/profiles/$id/delete/': typeof mainmodulesProfilesIdDeleteIndexRoute
  '/(main)/(modules)/profiles/$id/edit/': typeof mainmodulesProfilesIdEditIndexRoute
  '/(main)/(modules)/transactions/$id/delete/': typeof mainmodulesTransactionsIdDeleteIndexRoute
  '/(main)/(modules)/transactions/periods/create/': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/(main)/(modules)/transactions/reports/$id/': typeof mainmodulesTransactionsReportsIdIndexRoute
  '/(main)/(modules)/transactions/reports/create/': typeof mainmodulesTransactionsReportsCreateIndexRoute
  '/(main)/(modules)/transactions/reports/generate/': typeof mainmodulesTransactionsReportsGenerateIndexRoute
  '/(main)/(modules)/access-control/roles/$id/changes/': typeof mainmodulesAccessControlRolesIdChangesIndexRoute
  '/(main)/(modules)/access-control/roles/$id/delete/': typeof mainmodulesAccessControlRolesIdDeleteIndexRoute
  '/(main)/(modules)/access-control/roles/$id/edit/': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/(main)/(modules)/access-control/users/$username/changes/': typeof mainmodulesAccessControlUsersUsernameChangesIndexRoute
  '/(main)/(modules)/access-control/users/$username/edit/': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/(main)/(modules)/collaterals/reports/$id/delete/': typeof mainmodulesCollateralsReportsIdDeleteIndexRoute
  '/(main)/(modules)/collaterals/reports/$id/edit/': typeof mainmodulesCollateralsReportsIdEditIndexRoute
  '/(main)/(modules)/loans/purposes/$id/edit/': typeof mainmodulesLoansPurposesIdEditIndexRoute
  '/(main)/(modules)/loans/reports/$id/delete/': typeof mainmodulesLoansReportsIdDeleteIndexRoute
  '/(main)/(modules)/loans/reports/$id/edit/': typeof mainmodulesLoansReportsIdEditIndexRoute
  '/(main)/(modules)/transactions/reports/$id/delete/': typeof mainmodulesTransactionsReportsIdDeleteIndexRoute
  '/(main)/(modules)/transactions/reports/$id/edit/': typeof mainmodulesTransactionsReportsIdEditIndexRoute
  '/(main)/(modules)/transactions/reports/receipt/create/': typeof mainmodulesTransactionsReportsReceiptCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/logout/'
    | '/reset-password/'
    | '/access-control/'
    | '/account-statements/'
    | '/adjustment-notes/'
    | '/amortizations/'
    | '/collaterals/'
    | '/follow-ups/'
    | '/loans/'
    | '/profiles/'
    | '/projects/'
    | '/transactions/'
    | '/adjustment-notes/$id/'
    | '/adjustment-notes/create/'
    | '/collaterals/$id/'
    | '/collaterals/create/'
    | '/collaterals/reports/'
    | '/finance/expenses/'
    | '/finance/incomes/'
    | '/finance/projections/'
    | '/follow-ups/$id/'
    | '/follow-ups/create/'
    | '/loans/$id/'
    | '/loans/create/'
    | '/loans/purposes/'
    | '/loans/reports/'
    | '/profiles/$id/'
    | '/profiles/create/'
    | '/projects/create/'
    | '/projects/settings/'
    | '/transactions/$id/'
    | '/transactions/create/'
    | '/transactions/periods/'
    | '/transactions/reports/'
    | '/access-control/roles/$id/'
    | '/access-control/roles/create/'
    | '/access-control/users/$username/'
    | '/access-control/users/create/'
    | '/adjustment-notes/$id/delete/'
    | '/collaterals/$id/changes/'
    | '/collaterals/$id/delete/'
    | '/collaterals/$id/edit/'
    | '/collaterals/$id/settings/'
    | '/collaterals/reports/$id/'
    | '/collaterals/reports/create/'
    | '/collaterals/reports/generate/'
    | '/follow-ups/$id/edit/'
    | '/loans/$id/changes/'
    | '/loans/$id/delete/'
    | '/loans/$id/settings/'
    | '/loans/purposes/create/'
    | '/loans/reports/$id/'
    | '/loans/reports/create/'
    | '/loans/reports/generate/'
    | '/profiles/$id/changes/'
    | '/profiles/$id/delete/'
    | '/profiles/$id/edit/'
    | '/transactions/$id/delete/'
    | '/transactions/periods/create/'
    | '/transactions/reports/$id/'
    | '/transactions/reports/create/'
    | '/transactions/reports/generate/'
    | '/access-control/roles/$id/changes/'
    | '/access-control/roles/$id/delete/'
    | '/access-control/roles/$id/edit/'
    | '/access-control/users/$username/changes/'
    | '/access-control/users/$username/edit/'
    | '/collaterals/reports/$id/delete/'
    | '/collaterals/reports/$id/edit/'
    | '/loans/purposes/$id/edit/'
    | '/loans/reports/$id/delete/'
    | '/loans/reports/$id/edit/'
    | '/transactions/reports/$id/delete/'
    | '/transactions/reports/$id/edit/'
    | '/transactions/reports/receipt/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/access-control'
    | '/account-statements'
    | '/adjustment-notes'
    | '/amortizations'
    | '/collaterals'
    | '/follow-ups'
    | '/loans'
    | '/profiles'
    | '/projects'
    | '/transactions'
    | '/adjustment-notes/$id'
    | '/adjustment-notes/create'
    | '/collaterals/$id'
    | '/collaterals/create'
    | '/collaterals/reports'
    | '/finance/expenses'
    | '/finance/incomes'
    | '/finance/projections'
    | '/follow-ups/$id'
    | '/follow-ups/create'
    | '/loans/$id'
    | '/loans/create'
    | '/loans/purposes'
    | '/loans/reports'
    | '/profiles/$id'
    | '/profiles/create'
    | '/projects/create'
    | '/projects/settings'
    | '/transactions/$id'
    | '/transactions/create'
    | '/transactions/periods'
    | '/transactions/reports'
    | '/access-control/roles/$id'
    | '/access-control/roles/create'
    | '/access-control/users/$username'
    | '/access-control/users/create'
    | '/adjustment-notes/$id/delete'
    | '/collaterals/$id/changes'
    | '/collaterals/$id/delete'
    | '/collaterals/$id/edit'
    | '/collaterals/$id/settings'
    | '/collaterals/reports/$id'
    | '/collaterals/reports/create'
    | '/collaterals/reports/generate'
    | '/follow-ups/$id/edit'
    | '/loans/$id/changes'
    | '/loans/$id/delete'
    | '/loans/$id/settings'
    | '/loans/purposes/create'
    | '/loans/reports/$id'
    | '/loans/reports/create'
    | '/loans/reports/generate'
    | '/profiles/$id/changes'
    | '/profiles/$id/delete'
    | '/profiles/$id/edit'
    | '/transactions/$id/delete'
    | '/transactions/periods/create'
    | '/transactions/reports/$id'
    | '/transactions/reports/create'
    | '/transactions/reports/generate'
    | '/access-control/roles/$id/changes'
    | '/access-control/roles/$id/delete'
    | '/access-control/roles/$id/edit'
    | '/access-control/users/$username/changes'
    | '/access-control/users/$username/edit'
    | '/collaterals/reports/$id/delete'
    | '/collaterals/reports/$id/edit'
    | '/loans/purposes/$id/edit'
    | '/loans/reports/$id/delete'
    | '/loans/reports/$id/edit'
    | '/transactions/reports/$id/delete'
    | '/transactions/reports/$id/edit'
    | '/transactions/reports/receipt/create'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/(modules)'
    | '/(main)/'
    | '/login/'
    | '/logout/'
    | '/(main)/reset-password/'
    | '/(main)/(modules)/access-control/'
    | '/(main)/(modules)/account-statements/'
    | '/(main)/(modules)/adjustment-notes/'
    | '/(main)/(modules)/amortizations/'
    | '/(main)/(modules)/collaterals/'
    | '/(main)/(modules)/follow-ups/'
    | '/(main)/(modules)/loans/'
    | '/(main)/(modules)/profiles/'
    | '/(main)/(modules)/projects/'
    | '/(main)/(modules)/transactions/'
    | '/(main)/(modules)/adjustment-notes/$id/'
    | '/(main)/(modules)/adjustment-notes/create/'
    | '/(main)/(modules)/collaterals/$id/'
    | '/(main)/(modules)/collaterals/create/'
    | '/(main)/(modules)/collaterals/reports/'
    | '/(main)/(modules)/finance/expenses/'
    | '/(main)/(modules)/finance/incomes/'
    | '/(main)/(modules)/finance/projections/'
    | '/(main)/(modules)/follow-ups/$id/'
    | '/(main)/(modules)/follow-ups/create/'
    | '/(main)/(modules)/loans/$id/'
    | '/(main)/(modules)/loans/create/'
    | '/(main)/(modules)/loans/purposes/'
    | '/(main)/(modules)/loans/reports/'
    | '/(main)/(modules)/profiles/$id/'
    | '/(main)/(modules)/profiles/create/'
    | '/(main)/(modules)/projects/create/'
    | '/(main)/(modules)/projects/settings/'
    | '/(main)/(modules)/transactions/$id/'
    | '/(main)/(modules)/transactions/create/'
    | '/(main)/(modules)/transactions/periods/'
    | '/(main)/(modules)/transactions/reports/'
    | '/(main)/(modules)/access-control/roles/$id/'
    | '/(main)/(modules)/access-control/roles/create/'
    | '/(main)/(modules)/access-control/users/$username/'
    | '/(main)/(modules)/access-control/users/create/'
    | '/(main)/(modules)/adjustment-notes/$id/delete/'
    | '/(main)/(modules)/collaterals/$id/changes/'
    | '/(main)/(modules)/collaterals/$id/delete/'
    | '/(main)/(modules)/collaterals/$id/edit/'
    | '/(main)/(modules)/collaterals/$id/settings/'
    | '/(main)/(modules)/collaterals/reports/$id/'
    | '/(main)/(modules)/collaterals/reports/create/'
    | '/(main)/(modules)/collaterals/reports/generate/'
    | '/(main)/(modules)/follow-ups/$id/edit/'
    | '/(main)/(modules)/loans/$id/changes/'
    | '/(main)/(modules)/loans/$id/delete/'
    | '/(main)/(modules)/loans/$id/settings/'
    | '/(main)/(modules)/loans/purposes/create/'
    | '/(main)/(modules)/loans/reports/$id/'
    | '/(main)/(modules)/loans/reports/create/'
    | '/(main)/(modules)/loans/reports/generate/'
    | '/(main)/(modules)/profiles/$id/changes/'
    | '/(main)/(modules)/profiles/$id/delete/'
    | '/(main)/(modules)/profiles/$id/edit/'
    | '/(main)/(modules)/transactions/$id/delete/'
    | '/(main)/(modules)/transactions/periods/create/'
    | '/(main)/(modules)/transactions/reports/$id/'
    | '/(main)/(modules)/transactions/reports/create/'
    | '/(main)/(modules)/transactions/reports/generate/'
    | '/(main)/(modules)/access-control/roles/$id/changes/'
    | '/(main)/(modules)/access-control/roles/$id/delete/'
    | '/(main)/(modules)/access-control/roles/$id/edit/'
    | '/(main)/(modules)/access-control/users/$username/changes/'
    | '/(main)/(modules)/access-control/users/$username/edit/'
    | '/(main)/(modules)/collaterals/reports/$id/delete/'
    | '/(main)/(modules)/collaterals/reports/$id/edit/'
    | '/(main)/(modules)/loans/purposes/$id/edit/'
    | '/(main)/(modules)/loans/reports/$id/delete/'
    | '/(main)/(modules)/loans/reports/$id/edit/'
    | '/(main)/(modules)/transactions/reports/$id/delete/'
    | '/(main)/(modules)/transactions/reports/$id/edit/'
    | '/(main)/(modules)/transactions/reports/receipt/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(modules)': {
      id: '/(main)/(modules)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainmodulesRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/reset-password/': {
      id: '/(main)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof mainResetPasswordIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(modules)/transactions/': {
      id: '/(main)/(modules)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof mainmodulesTransactionsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/projects/': {
      id: '/(main)/(modules)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof mainmodulesProjectsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/': {
      id: '/(main)/(modules)/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof mainmodulesProfilesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/': {
      id: '/(main)/(modules)/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof mainmodulesLoansIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/': {
      id: '/(main)/(modules)/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof mainmodulesFollowUpsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/': {
      id: '/(main)/(modules)/collaterals/'
      path: '/collaterals'
      fullPath: '/collaterals/'
      preLoaderRoute: typeof mainmodulesCollateralsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/amortizations/': {
      id: '/(main)/(modules)/amortizations/'
      path: '/amortizations'
      fullPath: '/amortizations/'
      preLoaderRoute: typeof mainmodulesAmortizationsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/': {
      id: '/(main)/(modules)/adjustment-notes/'
      path: '/adjustment-notes'
      fullPath: '/adjustment-notes/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/account-statements/': {
      id: '/(main)/(modules)/account-statements/'
      path: '/account-statements'
      fullPath: '/account-statements/'
      preLoaderRoute: typeof mainmodulesAccountStatementsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/': {
      id: '/(main)/(modules)/access-control/'
      path: '/access-control'
      fullPath: '/access-control/'
      preLoaderRoute: typeof mainmodulesAccessControlIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/': {
      id: '/(main)/(modules)/transactions/reports/'
      path: '/transactions/reports'
      fullPath: '/transactions/reports/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/periods/': {
      id: '/(main)/(modules)/transactions/periods/'
      path: '/transactions/periods'
      fullPath: '/transactions/periods/'
      preLoaderRoute: typeof mainmodulesTransactionsPeriodsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/create/': {
      id: '/(main)/(modules)/transactions/create/'
      path: '/transactions/create'
      fullPath: '/transactions/create/'
      preLoaderRoute: typeof mainmodulesTransactionsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/$id/': {
      id: '/(main)/(modules)/transactions/$id/'
      path: '/transactions/$id'
      fullPath: '/transactions/$id/'
      preLoaderRoute: typeof mainmodulesTransactionsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/projects/settings/': {
      id: '/(main)/(modules)/projects/settings/'
      path: '/projects/settings'
      fullPath: '/projects/settings/'
      preLoaderRoute: typeof mainmodulesProjectsSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/projects/create/': {
      id: '/(main)/(modules)/projects/create/'
      path: '/projects/create'
      fullPath: '/projects/create/'
      preLoaderRoute: typeof mainmodulesProjectsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/create/': {
      id: '/(main)/(modules)/profiles/create/'
      path: '/profiles/create'
      fullPath: '/profiles/create/'
      preLoaderRoute: typeof mainmodulesProfilesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/': {
      id: '/(main)/(modules)/profiles/$id/'
      path: '/profiles/$id'
      fullPath: '/profiles/$id/'
      preLoaderRoute: typeof mainmodulesProfilesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/': {
      id: '/(main)/(modules)/loans/reports/'
      path: '/loans/reports'
      fullPath: '/loans/reports/'
      preLoaderRoute: typeof mainmodulesLoansReportsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purposes/': {
      id: '/(main)/(modules)/loans/purposes/'
      path: '/loans/purposes'
      fullPath: '/loans/purposes/'
      preLoaderRoute: typeof mainmodulesLoansPurposesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/create/': {
      id: '/(main)/(modules)/loans/create/'
      path: '/loans/create'
      fullPath: '/loans/create/'
      preLoaderRoute: typeof mainmodulesLoansCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/': {
      id: '/(main)/(modules)/loans/$id/'
      path: '/loans/$id'
      fullPath: '/loans/$id/'
      preLoaderRoute: typeof mainmodulesLoansIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/create/': {
      id: '/(main)/(modules)/follow-ups/create/'
      path: '/follow-ups/create'
      fullPath: '/follow-ups/create/'
      preLoaderRoute: typeof mainmodulesFollowUpsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/$id/': {
      id: '/(main)/(modules)/follow-ups/$id/'
      path: '/follow-ups/$id'
      fullPath: '/follow-ups/$id/'
      preLoaderRoute: typeof mainmodulesFollowUpsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/projections/': {
      id: '/(main)/(modules)/finance/projections/'
      path: '/finance/projections'
      fullPath: '/finance/projections/'
      preLoaderRoute: typeof mainmodulesFinanceProjectionsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/incomes/': {
      id: '/(main)/(modules)/finance/incomes/'
      path: '/finance/incomes'
      fullPath: '/finance/incomes/'
      preLoaderRoute: typeof mainmodulesFinanceIncomesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/expenses/': {
      id: '/(main)/(modules)/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/finance/expenses/'
      preLoaderRoute: typeof mainmodulesFinanceExpensesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/': {
      id: '/(main)/(modules)/collaterals/reports/'
      path: '/collaterals/reports'
      fullPath: '/collaterals/reports/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/create/': {
      id: '/(main)/(modules)/collaterals/create/'
      path: '/collaterals/create'
      fullPath: '/collaterals/create/'
      preLoaderRoute: typeof mainmodulesCollateralsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/': {
      id: '/(main)/(modules)/collaterals/$id/'
      path: '/collaterals/$id'
      fullPath: '/collaterals/$id/'
      preLoaderRoute: typeof mainmodulesCollateralsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/create/': {
      id: '/(main)/(modules)/adjustment-notes/create/'
      path: '/adjustment-notes/create'
      fullPath: '/adjustment-notes/create/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/$id/': {
      id: '/(main)/(modules)/adjustment-notes/$id/'
      path: '/adjustment-notes/$id'
      fullPath: '/adjustment-notes/$id/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/generate/': {
      id: '/(main)/(modules)/transactions/reports/generate/'
      path: '/transactions/reports/generate'
      fullPath: '/transactions/reports/generate/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsGenerateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/create/': {
      id: '/(main)/(modules)/transactions/reports/create/'
      path: '/transactions/reports/create'
      fullPath: '/transactions/reports/create/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/$id/': {
      id: '/(main)/(modules)/transactions/reports/$id/'
      path: '/transactions/reports/$id'
      fullPath: '/transactions/reports/$id/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/periods/create/': {
      id: '/(main)/(modules)/transactions/periods/create/'
      path: '/transactions/periods/create'
      fullPath: '/transactions/periods/create/'
      preLoaderRoute: typeof mainmodulesTransactionsPeriodsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/$id/delete/': {
      id: '/(main)/(modules)/transactions/$id/delete/'
      path: '/transactions/$id/delete'
      fullPath: '/transactions/$id/delete/'
      preLoaderRoute: typeof mainmodulesTransactionsIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/edit/': {
      id: '/(main)/(modules)/profiles/$id/edit/'
      path: '/profiles/$id/edit'
      fullPath: '/profiles/$id/edit/'
      preLoaderRoute: typeof mainmodulesProfilesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/delete/': {
      id: '/(main)/(modules)/profiles/$id/delete/'
      path: '/profiles/$id/delete'
      fullPath: '/profiles/$id/delete/'
      preLoaderRoute: typeof mainmodulesProfilesIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/changes/': {
      id: '/(main)/(modules)/profiles/$id/changes/'
      path: '/profiles/$id/changes'
      fullPath: '/profiles/$id/changes/'
      preLoaderRoute: typeof mainmodulesProfilesIdChangesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/generate/': {
      id: '/(main)/(modules)/loans/reports/generate/'
      path: '/loans/reports/generate'
      fullPath: '/loans/reports/generate/'
      preLoaderRoute: typeof mainmodulesLoansReportsGenerateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/create/': {
      id: '/(main)/(modules)/loans/reports/create/'
      path: '/loans/reports/create'
      fullPath: '/loans/reports/create/'
      preLoaderRoute: typeof mainmodulesLoansReportsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/$id/': {
      id: '/(main)/(modules)/loans/reports/$id/'
      path: '/loans/reports/$id'
      fullPath: '/loans/reports/$id/'
      preLoaderRoute: typeof mainmodulesLoansReportsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purposes/create/': {
      id: '/(main)/(modules)/loans/purposes/create/'
      path: '/loans/purposes/create'
      fullPath: '/loans/purposes/create/'
      preLoaderRoute: typeof mainmodulesLoansPurposesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/settings/': {
      id: '/(main)/(modules)/loans/$id/settings/'
      path: '/loans/$id/settings'
      fullPath: '/loans/$id/settings/'
      preLoaderRoute: typeof mainmodulesLoansIdSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/delete/': {
      id: '/(main)/(modules)/loans/$id/delete/'
      path: '/loans/$id/delete'
      fullPath: '/loans/$id/delete/'
      preLoaderRoute: typeof mainmodulesLoansIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/changes/': {
      id: '/(main)/(modules)/loans/$id/changes/'
      path: '/loans/$id/changes'
      fullPath: '/loans/$id/changes/'
      preLoaderRoute: typeof mainmodulesLoansIdChangesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/$id/edit/': {
      id: '/(main)/(modules)/follow-ups/$id/edit/'
      path: '/follow-ups/$id/edit'
      fullPath: '/follow-ups/$id/edit/'
      preLoaderRoute: typeof mainmodulesFollowUpsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/generate/': {
      id: '/(main)/(modules)/collaterals/reports/generate/'
      path: '/collaterals/reports/generate'
      fullPath: '/collaterals/reports/generate/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsGenerateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/create/': {
      id: '/(main)/(modules)/collaterals/reports/create/'
      path: '/collaterals/reports/create'
      fullPath: '/collaterals/reports/create/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/$id/': {
      id: '/(main)/(modules)/collaterals/reports/$id/'
      path: '/collaterals/reports/$id'
      fullPath: '/collaterals/reports/$id/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/settings/': {
      id: '/(main)/(modules)/collaterals/$id/settings/'
      path: '/collaterals/$id/settings'
      fullPath: '/collaterals/$id/settings/'
      preLoaderRoute: typeof mainmodulesCollateralsIdSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/edit/': {
      id: '/(main)/(modules)/collaterals/$id/edit/'
      path: '/collaterals/$id/edit'
      fullPath: '/collaterals/$id/edit/'
      preLoaderRoute: typeof mainmodulesCollateralsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/delete/': {
      id: '/(main)/(modules)/collaterals/$id/delete/'
      path: '/collaterals/$id/delete'
      fullPath: '/collaterals/$id/delete/'
      preLoaderRoute: typeof mainmodulesCollateralsIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/changes/': {
      id: '/(main)/(modules)/collaterals/$id/changes/'
      path: '/collaterals/$id/changes'
      fullPath: '/collaterals/$id/changes/'
      preLoaderRoute: typeof mainmodulesCollateralsIdChangesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/$id/delete/': {
      id: '/(main)/(modules)/adjustment-notes/$id/delete/'
      path: '/adjustment-notes/$id/delete'
      fullPath: '/adjustment-notes/$id/delete/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/create/': {
      id: '/(main)/(modules)/access-control/users/create/'
      path: '/access-control/users/create'
      fullPath: '/access-control/users/create/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/$username/': {
      id: '/(main)/(modules)/access-control/users/$username/'
      path: '/access-control/users/$username'
      fullPath: '/access-control/users/$username/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersUsernameIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/create/': {
      id: '/(main)/(modules)/access-control/roles/create/'
      path: '/access-control/roles/create'
      fullPath: '/access-control/roles/create/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/': {
      id: '/(main)/(modules)/access-control/roles/$id/'
      path: '/access-control/roles/$id'
      fullPath: '/access-control/roles/$id/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/receipt/create/': {
      id: '/(main)/(modules)/transactions/reports/receipt/create/'
      path: '/transactions/reports/receipt/create'
      fullPath: '/transactions/reports/receipt/create/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsReceiptCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/$id/edit/': {
      id: '/(main)/(modules)/transactions/reports/$id/edit/'
      path: '/transactions/reports/$id/edit'
      fullPath: '/transactions/reports/$id/edit/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/reports/$id/delete/': {
      id: '/(main)/(modules)/transactions/reports/$id/delete/'
      path: '/transactions/reports/$id/delete'
      fullPath: '/transactions/reports/$id/delete/'
      preLoaderRoute: typeof mainmodulesTransactionsReportsIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/$id/edit/': {
      id: '/(main)/(modules)/loans/reports/$id/edit/'
      path: '/loans/reports/$id/edit'
      fullPath: '/loans/reports/$id/edit/'
      preLoaderRoute: typeof mainmodulesLoansReportsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/reports/$id/delete/': {
      id: '/(main)/(modules)/loans/reports/$id/delete/'
      path: '/loans/reports/$id/delete'
      fullPath: '/loans/reports/$id/delete/'
      preLoaderRoute: typeof mainmodulesLoansReportsIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purposes/$id/edit/': {
      id: '/(main)/(modules)/loans/purposes/$id/edit/'
      path: '/loans/purposes/$id/edit'
      fullPath: '/loans/purposes/$id/edit/'
      preLoaderRoute: typeof mainmodulesLoansPurposesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/$id/edit/': {
      id: '/(main)/(modules)/collaterals/reports/$id/edit/'
      path: '/collaterals/reports/$id/edit'
      fullPath: '/collaterals/reports/$id/edit/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/reports/$id/delete/': {
      id: '/(main)/(modules)/collaterals/reports/$id/delete/'
      path: '/collaterals/reports/$id/delete'
      fullPath: '/collaterals/reports/$id/delete/'
      preLoaderRoute: typeof mainmodulesCollateralsReportsIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/$username/edit/': {
      id: '/(main)/(modules)/access-control/users/$username/edit/'
      path: '/access-control/users/$username/edit'
      fullPath: '/access-control/users/$username/edit/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersUsernameEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/$username/changes/': {
      id: '/(main)/(modules)/access-control/users/$username/changes/'
      path: '/access-control/users/$username/changes'
      fullPath: '/access-control/users/$username/changes/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersUsernameChangesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/edit/': {
      id: '/(main)/(modules)/access-control/roles/$id/edit/'
      path: '/access-control/roles/$id/edit'
      fullPath: '/access-control/roles/$id/edit/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/delete/': {
      id: '/(main)/(modules)/access-control/roles/$id/delete/'
      path: '/access-control/roles/$id/delete'
      fullPath: '/access-control/roles/$id/delete/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdDeleteIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/changes/': {
      id: '/(main)/(modules)/access-control/roles/$id/changes/'
      path: '/access-control/roles/$id/changes'
      fullPath: '/access-control/roles/$id/changes/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdChangesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
  }
}

interface mainmodulesRouteRouteChildren {
  mainmodulesAccessControlIndexRoute: typeof mainmodulesAccessControlIndexRoute
  mainmodulesAccountStatementsIndexRoute: typeof mainmodulesAccountStatementsIndexRoute
  mainmodulesAdjustmentNotesIndexRoute: typeof mainmodulesAdjustmentNotesIndexRoute
  mainmodulesAmortizationsIndexRoute: typeof mainmodulesAmortizationsIndexRoute
  mainmodulesCollateralsIndexRoute: typeof mainmodulesCollateralsIndexRoute
  mainmodulesFollowUpsIndexRoute: typeof mainmodulesFollowUpsIndexRoute
  mainmodulesLoansIndexRoute: typeof mainmodulesLoansIndexRoute
  mainmodulesProfilesIndexRoute: typeof mainmodulesProfilesIndexRoute
  mainmodulesProjectsIndexRoute: typeof mainmodulesProjectsIndexRoute
  mainmodulesTransactionsIndexRoute: typeof mainmodulesTransactionsIndexRoute
  mainmodulesAdjustmentNotesIdIndexRoute: typeof mainmodulesAdjustmentNotesIdIndexRoute
  mainmodulesAdjustmentNotesCreateIndexRoute: typeof mainmodulesAdjustmentNotesCreateIndexRoute
  mainmodulesCollateralsIdIndexRoute: typeof mainmodulesCollateralsIdIndexRoute
  mainmodulesCollateralsCreateIndexRoute: typeof mainmodulesCollateralsCreateIndexRoute
  mainmodulesCollateralsReportsIndexRoute: typeof mainmodulesCollateralsReportsIndexRoute
  mainmodulesFinanceExpensesIndexRoute: typeof mainmodulesFinanceExpensesIndexRoute
  mainmodulesFinanceIncomesIndexRoute: typeof mainmodulesFinanceIncomesIndexRoute
  mainmodulesFinanceProjectionsIndexRoute: typeof mainmodulesFinanceProjectionsIndexRoute
  mainmodulesFollowUpsIdIndexRoute: typeof mainmodulesFollowUpsIdIndexRoute
  mainmodulesFollowUpsCreateIndexRoute: typeof mainmodulesFollowUpsCreateIndexRoute
  mainmodulesLoansIdIndexRoute: typeof mainmodulesLoansIdIndexRoute
  mainmodulesLoansCreateIndexRoute: typeof mainmodulesLoansCreateIndexRoute
  mainmodulesLoansPurposesIndexRoute: typeof mainmodulesLoansPurposesIndexRoute
  mainmodulesLoansReportsIndexRoute: typeof mainmodulesLoansReportsIndexRoute
  mainmodulesProfilesIdIndexRoute: typeof mainmodulesProfilesIdIndexRoute
  mainmodulesProfilesCreateIndexRoute: typeof mainmodulesProfilesCreateIndexRoute
  mainmodulesProjectsCreateIndexRoute: typeof mainmodulesProjectsCreateIndexRoute
  mainmodulesProjectsSettingsIndexRoute: typeof mainmodulesProjectsSettingsIndexRoute
  mainmodulesTransactionsIdIndexRoute: typeof mainmodulesTransactionsIdIndexRoute
  mainmodulesTransactionsCreateIndexRoute: typeof mainmodulesTransactionsCreateIndexRoute
  mainmodulesTransactionsPeriodsIndexRoute: typeof mainmodulesTransactionsPeriodsIndexRoute
  mainmodulesTransactionsReportsIndexRoute: typeof mainmodulesTransactionsReportsIndexRoute
  mainmodulesAccessControlRolesIdIndexRoute: typeof mainmodulesAccessControlRolesIdIndexRoute
  mainmodulesAccessControlRolesCreateIndexRoute: typeof mainmodulesAccessControlRolesCreateIndexRoute
  mainmodulesAccessControlUsersUsernameIndexRoute: typeof mainmodulesAccessControlUsersUsernameIndexRoute
  mainmodulesAccessControlUsersCreateIndexRoute: typeof mainmodulesAccessControlUsersCreateIndexRoute
  mainmodulesAdjustmentNotesIdDeleteIndexRoute: typeof mainmodulesAdjustmentNotesIdDeleteIndexRoute
  mainmodulesCollateralsIdChangesIndexRoute: typeof mainmodulesCollateralsIdChangesIndexRoute
  mainmodulesCollateralsIdDeleteIndexRoute: typeof mainmodulesCollateralsIdDeleteIndexRoute
  mainmodulesCollateralsIdEditIndexRoute: typeof mainmodulesCollateralsIdEditIndexRoute
  mainmodulesCollateralsIdSettingsIndexRoute: typeof mainmodulesCollateralsIdSettingsIndexRoute
  mainmodulesCollateralsReportsIdIndexRoute: typeof mainmodulesCollateralsReportsIdIndexRoute
  mainmodulesCollateralsReportsCreateIndexRoute: typeof mainmodulesCollateralsReportsCreateIndexRoute
  mainmodulesCollateralsReportsGenerateIndexRoute: typeof mainmodulesCollateralsReportsGenerateIndexRoute
  mainmodulesFollowUpsIdEditIndexRoute: typeof mainmodulesFollowUpsIdEditIndexRoute
  mainmodulesLoansIdChangesIndexRoute: typeof mainmodulesLoansIdChangesIndexRoute
  mainmodulesLoansIdDeleteIndexRoute: typeof mainmodulesLoansIdDeleteIndexRoute
  mainmodulesLoansIdSettingsIndexRoute: typeof mainmodulesLoansIdSettingsIndexRoute
  mainmodulesLoansPurposesCreateIndexRoute: typeof mainmodulesLoansPurposesCreateIndexRoute
  mainmodulesLoansReportsIdIndexRoute: typeof mainmodulesLoansReportsIdIndexRoute
  mainmodulesLoansReportsCreateIndexRoute: typeof mainmodulesLoansReportsCreateIndexRoute
  mainmodulesLoansReportsGenerateIndexRoute: typeof mainmodulesLoansReportsGenerateIndexRoute
  mainmodulesProfilesIdChangesIndexRoute: typeof mainmodulesProfilesIdChangesIndexRoute
  mainmodulesProfilesIdDeleteIndexRoute: typeof mainmodulesProfilesIdDeleteIndexRoute
  mainmodulesProfilesIdEditIndexRoute: typeof mainmodulesProfilesIdEditIndexRoute
  mainmodulesTransactionsIdDeleteIndexRoute: typeof mainmodulesTransactionsIdDeleteIndexRoute
  mainmodulesTransactionsPeriodsCreateIndexRoute: typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  mainmodulesTransactionsReportsIdIndexRoute: typeof mainmodulesTransactionsReportsIdIndexRoute
  mainmodulesTransactionsReportsCreateIndexRoute: typeof mainmodulesTransactionsReportsCreateIndexRoute
  mainmodulesTransactionsReportsGenerateIndexRoute: typeof mainmodulesTransactionsReportsGenerateIndexRoute
  mainmodulesAccessControlRolesIdChangesIndexRoute: typeof mainmodulesAccessControlRolesIdChangesIndexRoute
  mainmodulesAccessControlRolesIdDeleteIndexRoute: typeof mainmodulesAccessControlRolesIdDeleteIndexRoute
  mainmodulesAccessControlRolesIdEditIndexRoute: typeof mainmodulesAccessControlRolesIdEditIndexRoute
  mainmodulesAccessControlUsersUsernameChangesIndexRoute: typeof mainmodulesAccessControlUsersUsernameChangesIndexRoute
  mainmodulesAccessControlUsersUsernameEditIndexRoute: typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  mainmodulesCollateralsReportsIdDeleteIndexRoute: typeof mainmodulesCollateralsReportsIdDeleteIndexRoute
  mainmodulesCollateralsReportsIdEditIndexRoute: typeof mainmodulesCollateralsReportsIdEditIndexRoute
  mainmodulesLoansPurposesIdEditIndexRoute: typeof mainmodulesLoansPurposesIdEditIndexRoute
  mainmodulesLoansReportsIdDeleteIndexRoute: typeof mainmodulesLoansReportsIdDeleteIndexRoute
  mainmodulesLoansReportsIdEditIndexRoute: typeof mainmodulesLoansReportsIdEditIndexRoute
  mainmodulesTransactionsReportsIdDeleteIndexRoute: typeof mainmodulesTransactionsReportsIdDeleteIndexRoute
  mainmodulesTransactionsReportsIdEditIndexRoute: typeof mainmodulesTransactionsReportsIdEditIndexRoute
  mainmodulesTransactionsReportsReceiptCreateIndexRoute: typeof mainmodulesTransactionsReportsReceiptCreateIndexRoute
}

const mainmodulesRouteRouteChildren: mainmodulesRouteRouteChildren = {
  mainmodulesAccessControlIndexRoute: mainmodulesAccessControlIndexRoute,
  mainmodulesAccountStatementsIndexRoute:
    mainmodulesAccountStatementsIndexRoute,
  mainmodulesAdjustmentNotesIndexRoute: mainmodulesAdjustmentNotesIndexRoute,
  mainmodulesAmortizationsIndexRoute: mainmodulesAmortizationsIndexRoute,
  mainmodulesCollateralsIndexRoute: mainmodulesCollateralsIndexRoute,
  mainmodulesFollowUpsIndexRoute: mainmodulesFollowUpsIndexRoute,
  mainmodulesLoansIndexRoute: mainmodulesLoansIndexRoute,
  mainmodulesProfilesIndexRoute: mainmodulesProfilesIndexRoute,
  mainmodulesProjectsIndexRoute: mainmodulesProjectsIndexRoute,
  mainmodulesTransactionsIndexRoute: mainmodulesTransactionsIndexRoute,
  mainmodulesAdjustmentNotesIdIndexRoute:
    mainmodulesAdjustmentNotesIdIndexRoute,
  mainmodulesAdjustmentNotesCreateIndexRoute:
    mainmodulesAdjustmentNotesCreateIndexRoute,
  mainmodulesCollateralsIdIndexRoute: mainmodulesCollateralsIdIndexRoute,
  mainmodulesCollateralsCreateIndexRoute:
    mainmodulesCollateralsCreateIndexRoute,
  mainmodulesCollateralsReportsIndexRoute:
    mainmodulesCollateralsReportsIndexRoute,
  mainmodulesFinanceExpensesIndexRoute: mainmodulesFinanceExpensesIndexRoute,
  mainmodulesFinanceIncomesIndexRoute: mainmodulesFinanceIncomesIndexRoute,
  mainmodulesFinanceProjectionsIndexRoute:
    mainmodulesFinanceProjectionsIndexRoute,
  mainmodulesFollowUpsIdIndexRoute: mainmodulesFollowUpsIdIndexRoute,
  mainmodulesFollowUpsCreateIndexRoute: mainmodulesFollowUpsCreateIndexRoute,
  mainmodulesLoansIdIndexRoute: mainmodulesLoansIdIndexRoute,
  mainmodulesLoansCreateIndexRoute: mainmodulesLoansCreateIndexRoute,
  mainmodulesLoansPurposesIndexRoute: mainmodulesLoansPurposesIndexRoute,
  mainmodulesLoansReportsIndexRoute: mainmodulesLoansReportsIndexRoute,
  mainmodulesProfilesIdIndexRoute: mainmodulesProfilesIdIndexRoute,
  mainmodulesProfilesCreateIndexRoute: mainmodulesProfilesCreateIndexRoute,
  mainmodulesProjectsCreateIndexRoute: mainmodulesProjectsCreateIndexRoute,
  mainmodulesProjectsSettingsIndexRoute: mainmodulesProjectsSettingsIndexRoute,
  mainmodulesTransactionsIdIndexRoute: mainmodulesTransactionsIdIndexRoute,
  mainmodulesTransactionsCreateIndexRoute:
    mainmodulesTransactionsCreateIndexRoute,
  mainmodulesTransactionsPeriodsIndexRoute:
    mainmodulesTransactionsPeriodsIndexRoute,
  mainmodulesTransactionsReportsIndexRoute:
    mainmodulesTransactionsReportsIndexRoute,
  mainmodulesAccessControlRolesIdIndexRoute:
    mainmodulesAccessControlRolesIdIndexRoute,
  mainmodulesAccessControlRolesCreateIndexRoute:
    mainmodulesAccessControlRolesCreateIndexRoute,
  mainmodulesAccessControlUsersUsernameIndexRoute:
    mainmodulesAccessControlUsersUsernameIndexRoute,
  mainmodulesAccessControlUsersCreateIndexRoute:
    mainmodulesAccessControlUsersCreateIndexRoute,
  mainmodulesAdjustmentNotesIdDeleteIndexRoute:
    mainmodulesAdjustmentNotesIdDeleteIndexRoute,
  mainmodulesCollateralsIdChangesIndexRoute:
    mainmodulesCollateralsIdChangesIndexRoute,
  mainmodulesCollateralsIdDeleteIndexRoute:
    mainmodulesCollateralsIdDeleteIndexRoute,
  mainmodulesCollateralsIdEditIndexRoute:
    mainmodulesCollateralsIdEditIndexRoute,
  mainmodulesCollateralsIdSettingsIndexRoute:
    mainmodulesCollateralsIdSettingsIndexRoute,
  mainmodulesCollateralsReportsIdIndexRoute:
    mainmodulesCollateralsReportsIdIndexRoute,
  mainmodulesCollateralsReportsCreateIndexRoute:
    mainmodulesCollateralsReportsCreateIndexRoute,
  mainmodulesCollateralsReportsGenerateIndexRoute:
    mainmodulesCollateralsReportsGenerateIndexRoute,
  mainmodulesFollowUpsIdEditIndexRoute: mainmodulesFollowUpsIdEditIndexRoute,
  mainmodulesLoansIdChangesIndexRoute: mainmodulesLoansIdChangesIndexRoute,
  mainmodulesLoansIdDeleteIndexRoute: mainmodulesLoansIdDeleteIndexRoute,
  mainmodulesLoansIdSettingsIndexRoute: mainmodulesLoansIdSettingsIndexRoute,
  mainmodulesLoansPurposesCreateIndexRoute:
    mainmodulesLoansPurposesCreateIndexRoute,
  mainmodulesLoansReportsIdIndexRoute: mainmodulesLoansReportsIdIndexRoute,
  mainmodulesLoansReportsCreateIndexRoute:
    mainmodulesLoansReportsCreateIndexRoute,
  mainmodulesLoansReportsGenerateIndexRoute:
    mainmodulesLoansReportsGenerateIndexRoute,
  mainmodulesProfilesIdChangesIndexRoute:
    mainmodulesProfilesIdChangesIndexRoute,
  mainmodulesProfilesIdDeleteIndexRoute: mainmodulesProfilesIdDeleteIndexRoute,
  mainmodulesProfilesIdEditIndexRoute: mainmodulesProfilesIdEditIndexRoute,
  mainmodulesTransactionsIdDeleteIndexRoute:
    mainmodulesTransactionsIdDeleteIndexRoute,
  mainmodulesTransactionsPeriodsCreateIndexRoute:
    mainmodulesTransactionsPeriodsCreateIndexRoute,
  mainmodulesTransactionsReportsIdIndexRoute:
    mainmodulesTransactionsReportsIdIndexRoute,
  mainmodulesTransactionsReportsCreateIndexRoute:
    mainmodulesTransactionsReportsCreateIndexRoute,
  mainmodulesTransactionsReportsGenerateIndexRoute:
    mainmodulesTransactionsReportsGenerateIndexRoute,
  mainmodulesAccessControlRolesIdChangesIndexRoute:
    mainmodulesAccessControlRolesIdChangesIndexRoute,
  mainmodulesAccessControlRolesIdDeleteIndexRoute:
    mainmodulesAccessControlRolesIdDeleteIndexRoute,
  mainmodulesAccessControlRolesIdEditIndexRoute:
    mainmodulesAccessControlRolesIdEditIndexRoute,
  mainmodulesAccessControlUsersUsernameChangesIndexRoute:
    mainmodulesAccessControlUsersUsernameChangesIndexRoute,
  mainmodulesAccessControlUsersUsernameEditIndexRoute:
    mainmodulesAccessControlUsersUsernameEditIndexRoute,
  mainmodulesCollateralsReportsIdDeleteIndexRoute:
    mainmodulesCollateralsReportsIdDeleteIndexRoute,
  mainmodulesCollateralsReportsIdEditIndexRoute:
    mainmodulesCollateralsReportsIdEditIndexRoute,
  mainmodulesLoansPurposesIdEditIndexRoute:
    mainmodulesLoansPurposesIdEditIndexRoute,
  mainmodulesLoansReportsIdDeleteIndexRoute:
    mainmodulesLoansReportsIdDeleteIndexRoute,
  mainmodulesLoansReportsIdEditIndexRoute:
    mainmodulesLoansReportsIdEditIndexRoute,
  mainmodulesTransactionsReportsIdDeleteIndexRoute:
    mainmodulesTransactionsReportsIdDeleteIndexRoute,
  mainmodulesTransactionsReportsIdEditIndexRoute:
    mainmodulesTransactionsReportsIdEditIndexRoute,
  mainmodulesTransactionsReportsReceiptCreateIndexRoute:
    mainmodulesTransactionsReportsReceiptCreateIndexRoute,
}

const mainmodulesRouteRouteWithChildren =
  mainmodulesRouteRoute._addFileChildren(mainmodulesRouteRouteChildren)

interface mainRouteRouteChildren {
  mainmodulesRouteRoute: typeof mainmodulesRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
  mainResetPasswordIndexRoute: typeof mainResetPasswordIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainmodulesRouteRoute: mainmodulesRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
  mainResetPasswordIndexRoute: mainResetPasswordIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
