/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainmodulesRouteRouteImport } from './routes/(main)/(modules)/route'
import { Route as mainResetPasswordIndexRouteImport } from './routes/(main)/reset-password/index'
import { Route as mainmodulesTransactionsIndexRouteImport } from './routes/(main)/(modules)/transactions/index'
import { Route as mainmodulesReportsIndexRouteImport } from './routes/(main)/(modules)/reports/index'
import { Route as mainmodulesProfilesIndexRouteImport } from './routes/(main)/(modules)/profiles/index'
import { Route as mainmodulesLoansIndexRouteImport } from './routes/(main)/(modules)/loans/index'
import { Route as mainmodulesFollowUpsIndexRouteImport } from './routes/(main)/(modules)/follow-ups/index'
import { Route as mainmodulesCollateralsIndexRouteImport } from './routes/(main)/(modules)/collaterals/index'
import { Route as mainmodulesAmortizationsIndexRouteImport } from './routes/(main)/(modules)/amortizations/index'
import { Route as mainmodulesAdjustmentNotesIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/index'
import { Route as mainmodulesAccountStatementsIndexRouteImport } from './routes/(main)/(modules)/account-statements/index'
import { Route as mainmodulesAccessControlIndexRouteImport } from './routes/(main)/(modules)/access-control/index'
import { Route as mainmodulesTransactionsPeriodsIndexRouteImport } from './routes/(main)/(modules)/transactions/periods/index'
import { Route as mainmodulesTransactionsCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/create/index'
import { Route as mainmodulesTransactionsIdIndexRouteImport } from './routes/(main)/(modules)/transactions/$id/index'
import { Route as mainmodulesReportsGenerateIndexRouteImport } from './routes/(main)/(modules)/reports/generate/index'
import { Route as mainmodulesReportsCreateIndexRouteImport } from './routes/(main)/(modules)/reports/create/index'
import { Route as mainmodulesReportsIdIndexRouteImport } from './routes/(main)/(modules)/reports/$id/index'
import { Route as mainmodulesProjectsSettingsIndexRouteImport } from './routes/(main)/(modules)/projects/settings/index'
import { Route as mainmodulesProjectsCreateIndexRouteImport } from './routes/(main)/(modules)/projects/create/index'
import { Route as mainmodulesProfilesCreateIndexRouteImport } from './routes/(main)/(modules)/profiles/create/index'
import { Route as mainmodulesProfilesIdIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/index'
import { Route as mainmodulesLoansPurpousesIndexRouteImport } from './routes/(main)/(modules)/loans/purpouses/index'
import { Route as mainmodulesLoansCreateIndexRouteImport } from './routes/(main)/(modules)/loans/create/index'
import { Route as mainmodulesLoansIdIndexRouteImport } from './routes/(main)/(modules)/loans/$id/index'
import { Route as mainmodulesFollowUpsCreateIndexRouteImport } from './routes/(main)/(modules)/follow-ups/create/index'
import { Route as mainmodulesFollowUpsIdIndexRouteImport } from './routes/(main)/(modules)/follow-ups/$id/index'
import { Route as mainmodulesFinanceProjectionsIndexRouteImport } from './routes/(main)/(modules)/finance/projections/index'
import { Route as mainmodulesFinanceIncomesIndexRouteImport } from './routes/(main)/(modules)/finance/incomes/index'
import { Route as mainmodulesFinanceExpensesIndexRouteImport } from './routes/(main)/(modules)/finance/expenses/index'
import { Route as mainmodulesCollateralsCreateIndexRouteImport } from './routes/(main)/(modules)/collaterals/create/index'
import { Route as mainmodulesCollateralsIdIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/index'
import { Route as mainmodulesAdjustmentNotesCreateIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/create/index'
import { Route as mainmodulesAdjustmentNotesIdIndexRouteImport } from './routes/(main)/(modules)/adjustment-notes/$id/index'
import { Route as mainmodulesTransactionsReceiptReportTemplateCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/receipt-report-template/create/index'
import { Route as mainmodulesTransactionsPeriodsCreateIndexRouteImport } from './routes/(main)/(modules)/transactions/periods/create/index'
import { Route as mainmodulesReportsIdEditIndexRouteImport } from './routes/(main)/(modules)/reports/$id/edit/index'
import { Route as mainmodulesProfilesIdEditIndexRouteImport } from './routes/(main)/(modules)/profiles/$id/edit/index'
import { Route as mainmodulesLoansPurpousesCreateIndexRouteImport } from './routes/(main)/(modules)/loans/purpouses/create/index'
import { Route as mainmodulesLoansIdSettingsIndexRouteImport } from './routes/(main)/(modules)/loans/$id/settings/index'
import { Route as mainmodulesFollowUpsIdEditIndexRouteImport } from './routes/(main)/(modules)/follow-ups/$id/edit/index'
import { Route as mainmodulesCollateralsIdSettingsIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/settings/index'
import { Route as mainmodulesCollateralsIdEditIndexRouteImport } from './routes/(main)/(modules)/collaterals/$id/edit/index'
import { Route as mainmodulesAccessControlUsersCreateIndexRouteImport } from './routes/(main)/(modules)/access-control/users/create/index'
import { Route as mainmodulesAccessControlUsersUsernameIndexRouteImport } from './routes/(main)/(modules)/access-control/users/$username/index'
import { Route as mainmodulesAccessControlRolesCreateIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/create/index'
import { Route as mainmodulesAccessControlRolesIdIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/index'
import { Route as mainmodulesLoansPurpousesIdEditIndexRouteImport } from './routes/(main)/(modules)/loans/purpouses/$id/edit/index'
import { Route as mainmodulesAccessControlUsersUsernameEditIndexRouteImport } from './routes/(main)/(modules)/access-control/users/$username/edit/index'
import { Route as mainmodulesAccessControlRolesIdEditIndexRouteImport } from './routes/(main)/(modules)/access-control/roles/$id/edit/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainmodulesRouteRoute = mainmodulesRouteRouteImport.update({
  id: '/(modules)',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainResetPasswordIndexRoute = mainResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainmodulesTransactionsIndexRoute =
  mainmodulesTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesReportsIndexRoute = mainmodulesReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => mainmodulesRouteRoute,
} as any)
const mainmodulesProfilesIndexRoute =
  mainmodulesProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIndexRoute = mainmodulesLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => mainmodulesRouteRoute,
} as any)
const mainmodulesFollowUpsIndexRoute =
  mainmodulesFollowUpsIndexRouteImport.update({
    id: '/follow-ups/',
    path: '/follow-ups/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIndexRoute =
  mainmodulesCollateralsIndexRouteImport.update({
    id: '/collaterals/',
    path: '/collaterals/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAmortizationsIndexRoute =
  mainmodulesAmortizationsIndexRouteImport.update({
    id: '/amortizations/',
    path: '/amortizations/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesIndexRoute =
  mainmodulesAdjustmentNotesIndexRouteImport.update({
    id: '/adjustment-notes/',
    path: '/adjustment-notes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccountStatementsIndexRoute =
  mainmodulesAccountStatementsIndexRouteImport.update({
    id: '/account-statements/',
    path: '/account-statements/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlIndexRoute =
  mainmodulesAccessControlIndexRouteImport.update({
    id: '/access-control/',
    path: '/access-control/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsPeriodsIndexRoute =
  mainmodulesTransactionsPeriodsIndexRouteImport.update({
    id: '/transactions/periods/',
    path: '/transactions/periods/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsCreateIndexRoute =
  mainmodulesTransactionsCreateIndexRouteImport.update({
    id: '/transactions/create/',
    path: '/transactions/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsIdIndexRoute =
  mainmodulesTransactionsIdIndexRouteImport.update({
    id: '/transactions/$id/',
    path: '/transactions/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesReportsGenerateIndexRoute =
  mainmodulesReportsGenerateIndexRouteImport.update({
    id: '/reports/generate/',
    path: '/reports/generate/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesReportsCreateIndexRoute =
  mainmodulesReportsCreateIndexRouteImport.update({
    id: '/reports/create/',
    path: '/reports/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesReportsIdIndexRoute =
  mainmodulesReportsIdIndexRouteImport.update({
    id: '/reports/$id/',
    path: '/reports/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProjectsSettingsIndexRoute =
  mainmodulesProjectsSettingsIndexRouteImport.update({
    id: '/projects/settings/',
    path: '/projects/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProjectsCreateIndexRoute =
  mainmodulesProjectsCreateIndexRouteImport.update({
    id: '/projects/create/',
    path: '/projects/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesCreateIndexRoute =
  mainmodulesProfilesCreateIndexRouteImport.update({
    id: '/profiles/create/',
    path: '/profiles/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdIndexRoute =
  mainmodulesProfilesIdIndexRouteImport.update({
    id: '/profiles/$id/',
    path: '/profiles/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurpousesIndexRoute =
  mainmodulesLoansPurpousesIndexRouteImport.update({
    id: '/loans/purpouses/',
    path: '/loans/purpouses/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansCreateIndexRoute =
  mainmodulesLoansCreateIndexRouteImport.update({
    id: '/loans/create/',
    path: '/loans/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdIndexRoute = mainmodulesLoansIdIndexRouteImport.update({
  id: '/loans/$id/',
  path: '/loans/$id/',
  getParentRoute: () => mainmodulesRouteRoute,
} as any)
const mainmodulesFollowUpsCreateIndexRoute =
  mainmodulesFollowUpsCreateIndexRouteImport.update({
    id: '/follow-ups/create/',
    path: '/follow-ups/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFollowUpsIdIndexRoute =
  mainmodulesFollowUpsIdIndexRouteImport.update({
    id: '/follow-ups/$id/',
    path: '/follow-ups/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceProjectionsIndexRoute =
  mainmodulesFinanceProjectionsIndexRouteImport.update({
    id: '/finance/projections/',
    path: '/finance/projections/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceIncomesIndexRoute =
  mainmodulesFinanceIncomesIndexRouteImport.update({
    id: '/finance/incomes/',
    path: '/finance/incomes/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFinanceExpensesIndexRoute =
  mainmodulesFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsCreateIndexRoute =
  mainmodulesCollateralsCreateIndexRouteImport.update({
    id: '/collaterals/create/',
    path: '/collaterals/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdIndexRoute =
  mainmodulesCollateralsIdIndexRouteImport.update({
    id: '/collaterals/$id/',
    path: '/collaterals/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesCreateIndexRoute =
  mainmodulesAdjustmentNotesCreateIndexRouteImport.update({
    id: '/adjustment-notes/create/',
    path: '/adjustment-notes/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAdjustmentNotesIdIndexRoute =
  mainmodulesAdjustmentNotesIdIndexRouteImport.update({
    id: '/adjustment-notes/$id/',
    path: '/adjustment-notes/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute =
  mainmodulesTransactionsReceiptReportTemplateCreateIndexRouteImport.update({
    id: '/transactions/receipt-report-template/create/',
    path: '/transactions/receipt-report-template/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesTransactionsPeriodsCreateIndexRoute =
  mainmodulesTransactionsPeriodsCreateIndexRouteImport.update({
    id: '/transactions/periods/create/',
    path: '/transactions/periods/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesReportsIdEditIndexRoute =
  mainmodulesReportsIdEditIndexRouteImport.update({
    id: '/reports/$id/edit/',
    path: '/reports/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesProfilesIdEditIndexRoute =
  mainmodulesProfilesIdEditIndexRouteImport.update({
    id: '/profiles/$id/edit/',
    path: '/profiles/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurpousesCreateIndexRoute =
  mainmodulesLoansPurpousesCreateIndexRouteImport.update({
    id: '/loans/purpouses/create/',
    path: '/loans/purpouses/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansIdSettingsIndexRoute =
  mainmodulesLoansIdSettingsIndexRouteImport.update({
    id: '/loans/$id/settings/',
    path: '/loans/$id/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesFollowUpsIdEditIndexRoute =
  mainmodulesFollowUpsIdEditIndexRouteImport.update({
    id: '/follow-ups/$id/edit/',
    path: '/follow-ups/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdSettingsIndexRoute =
  mainmodulesCollateralsIdSettingsIndexRouteImport.update({
    id: '/collaterals/$id/settings/',
    path: '/collaterals/$id/settings/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesCollateralsIdEditIndexRoute =
  mainmodulesCollateralsIdEditIndexRouteImport.update({
    id: '/collaterals/$id/edit/',
    path: '/collaterals/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersCreateIndexRoute =
  mainmodulesAccessControlUsersCreateIndexRouteImport.update({
    id: '/access-control/users/create/',
    path: '/access-control/users/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersUsernameIndexRoute =
  mainmodulesAccessControlUsersUsernameIndexRouteImport.update({
    id: '/access-control/users/$username/',
    path: '/access-control/users/$username/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesCreateIndexRoute =
  mainmodulesAccessControlRolesCreateIndexRouteImport.update({
    id: '/access-control/roles/create/',
    path: '/access-control/roles/create/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdIndexRoute =
  mainmodulesAccessControlRolesIdIndexRouteImport.update({
    id: '/access-control/roles/$id/',
    path: '/access-control/roles/$id/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesLoansPurpousesIdEditIndexRoute =
  mainmodulesLoansPurpousesIdEditIndexRouteImport.update({
    id: '/loans/purpouses/$id/edit/',
    path: '/loans/purpouses/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlUsersUsernameEditIndexRoute =
  mainmodulesAccessControlUsersUsernameEditIndexRouteImport.update({
    id: '/access-control/users/$username/edit/',
    path: '/access-control/users/$username/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)
const mainmodulesAccessControlRolesIdEditIndexRoute =
  mainmodulesAccessControlRolesIdEditIndexRouteImport.update({
    id: '/access-control/roles/$id/edit/',
    path: '/access-control/roles/$id/edit/',
    getParentRoute: () => mainmodulesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/reset-password/': typeof mainResetPasswordIndexRoute
  '/access-control/': typeof mainmodulesAccessControlIndexRoute
  '/account-statements/': typeof mainmodulesAccountStatementsIndexRoute
  '/adjustment-notes/': typeof mainmodulesAdjustmentNotesIndexRoute
  '/amortizations/': typeof mainmodulesAmortizationsIndexRoute
  '/collaterals/': typeof mainmodulesCollateralsIndexRoute
  '/follow-ups/': typeof mainmodulesFollowUpsIndexRoute
  '/loans/': typeof mainmodulesLoansIndexRoute
  '/profiles/': typeof mainmodulesProfilesIndexRoute
  '/reports/': typeof mainmodulesReportsIndexRoute
  '/transactions/': typeof mainmodulesTransactionsIndexRoute
  '/adjustment-notes/$id/': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/adjustment-notes/create/': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/collaterals/$id/': typeof mainmodulesCollateralsIdIndexRoute
  '/collaterals/create/': typeof mainmodulesCollateralsCreateIndexRoute
  '/finance/expenses/': typeof mainmodulesFinanceExpensesIndexRoute
  '/finance/incomes/': typeof mainmodulesFinanceIncomesIndexRoute
  '/finance/projections/': typeof mainmodulesFinanceProjectionsIndexRoute
  '/follow-ups/$id/': typeof mainmodulesFollowUpsIdIndexRoute
  '/follow-ups/create/': typeof mainmodulesFollowUpsCreateIndexRoute
  '/loans/$id/': typeof mainmodulesLoansIdIndexRoute
  '/loans/create/': typeof mainmodulesLoansCreateIndexRoute
  '/loans/purpouses/': typeof mainmodulesLoansPurpousesIndexRoute
  '/profiles/$id/': typeof mainmodulesProfilesIdIndexRoute
  '/profiles/create/': typeof mainmodulesProfilesCreateIndexRoute
  '/projects/create/': typeof mainmodulesProjectsCreateIndexRoute
  '/projects/settings/': typeof mainmodulesProjectsSettingsIndexRoute
  '/reports/$id/': typeof mainmodulesReportsIdIndexRoute
  '/reports/create/': typeof mainmodulesReportsCreateIndexRoute
  '/reports/generate/': typeof mainmodulesReportsGenerateIndexRoute
  '/transactions/$id/': typeof mainmodulesTransactionsIdIndexRoute
  '/transactions/create/': typeof mainmodulesTransactionsCreateIndexRoute
  '/transactions/periods/': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/access-control/roles/$id/': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/access-control/roles/create/': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/access-control/users/$username/': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/access-control/users/create/': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/collaterals/$id/edit/': typeof mainmodulesCollateralsIdEditIndexRoute
  '/collaterals/$id/settings/': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/follow-ups/$id/edit/': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/loans/$id/settings/': typeof mainmodulesLoansIdSettingsIndexRoute
  '/loans/purpouses/create/': typeof mainmodulesLoansPurpousesCreateIndexRoute
  '/profiles/$id/edit/': typeof mainmodulesProfilesIdEditIndexRoute
  '/reports/$id/edit/': typeof mainmodulesReportsIdEditIndexRoute
  '/transactions/periods/create/': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/transactions/receipt-report-template/create/': typeof mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute
  '/access-control/roles/$id/edit/': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/access-control/users/$username/edit/': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/loans/purpouses/$id/edit/': typeof mainmodulesLoansPurpousesIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/reset-password': typeof mainResetPasswordIndexRoute
  '/access-control': typeof mainmodulesAccessControlIndexRoute
  '/account-statements': typeof mainmodulesAccountStatementsIndexRoute
  '/adjustment-notes': typeof mainmodulesAdjustmentNotesIndexRoute
  '/amortizations': typeof mainmodulesAmortizationsIndexRoute
  '/collaterals': typeof mainmodulesCollateralsIndexRoute
  '/follow-ups': typeof mainmodulesFollowUpsIndexRoute
  '/loans': typeof mainmodulesLoansIndexRoute
  '/profiles': typeof mainmodulesProfilesIndexRoute
  '/reports': typeof mainmodulesReportsIndexRoute
  '/transactions': typeof mainmodulesTransactionsIndexRoute
  '/adjustment-notes/$id': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/adjustment-notes/create': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/collaterals/$id': typeof mainmodulesCollateralsIdIndexRoute
  '/collaterals/create': typeof mainmodulesCollateralsCreateIndexRoute
  '/finance/expenses': typeof mainmodulesFinanceExpensesIndexRoute
  '/finance/incomes': typeof mainmodulesFinanceIncomesIndexRoute
  '/finance/projections': typeof mainmodulesFinanceProjectionsIndexRoute
  '/follow-ups/$id': typeof mainmodulesFollowUpsIdIndexRoute
  '/follow-ups/create': typeof mainmodulesFollowUpsCreateIndexRoute
  '/loans/$id': typeof mainmodulesLoansIdIndexRoute
  '/loans/create': typeof mainmodulesLoansCreateIndexRoute
  '/loans/purpouses': typeof mainmodulesLoansPurpousesIndexRoute
  '/profiles/$id': typeof mainmodulesProfilesIdIndexRoute
  '/profiles/create': typeof mainmodulesProfilesCreateIndexRoute
  '/projects/create': typeof mainmodulesProjectsCreateIndexRoute
  '/projects/settings': typeof mainmodulesProjectsSettingsIndexRoute
  '/reports/$id': typeof mainmodulesReportsIdIndexRoute
  '/reports/create': typeof mainmodulesReportsCreateIndexRoute
  '/reports/generate': typeof mainmodulesReportsGenerateIndexRoute
  '/transactions/$id': typeof mainmodulesTransactionsIdIndexRoute
  '/transactions/create': typeof mainmodulesTransactionsCreateIndexRoute
  '/transactions/periods': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/access-control/roles/$id': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/access-control/roles/create': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/access-control/users/$username': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/access-control/users/create': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/collaterals/$id/edit': typeof mainmodulesCollateralsIdEditIndexRoute
  '/collaterals/$id/settings': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/follow-ups/$id/edit': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/loans/$id/settings': typeof mainmodulesLoansIdSettingsIndexRoute
  '/loans/purpouses/create': typeof mainmodulesLoansPurpousesCreateIndexRoute
  '/profiles/$id/edit': typeof mainmodulesProfilesIdEditIndexRoute
  '/reports/$id/edit': typeof mainmodulesReportsIdEditIndexRoute
  '/transactions/periods/create': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/transactions/receipt-report-template/create': typeof mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute
  '/access-control/roles/$id/edit': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/access-control/users/$username/edit': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/loans/purpouses/$id/edit': typeof mainmodulesLoansPurpousesIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/(modules)': typeof mainmodulesRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/(main)/reset-password/': typeof mainResetPasswordIndexRoute
  '/(main)/(modules)/access-control/': typeof mainmodulesAccessControlIndexRoute
  '/(main)/(modules)/account-statements/': typeof mainmodulesAccountStatementsIndexRoute
  '/(main)/(modules)/adjustment-notes/': typeof mainmodulesAdjustmentNotesIndexRoute
  '/(main)/(modules)/amortizations/': typeof mainmodulesAmortizationsIndexRoute
  '/(main)/(modules)/collaterals/': typeof mainmodulesCollateralsIndexRoute
  '/(main)/(modules)/follow-ups/': typeof mainmodulesFollowUpsIndexRoute
  '/(main)/(modules)/loans/': typeof mainmodulesLoansIndexRoute
  '/(main)/(modules)/profiles/': typeof mainmodulesProfilesIndexRoute
  '/(main)/(modules)/reports/': typeof mainmodulesReportsIndexRoute
  '/(main)/(modules)/transactions/': typeof mainmodulesTransactionsIndexRoute
  '/(main)/(modules)/adjustment-notes/$id/': typeof mainmodulesAdjustmentNotesIdIndexRoute
  '/(main)/(modules)/adjustment-notes/create/': typeof mainmodulesAdjustmentNotesCreateIndexRoute
  '/(main)/(modules)/collaterals/$id/': typeof mainmodulesCollateralsIdIndexRoute
  '/(main)/(modules)/collaterals/create/': typeof mainmodulesCollateralsCreateIndexRoute
  '/(main)/(modules)/finance/expenses/': typeof mainmodulesFinanceExpensesIndexRoute
  '/(main)/(modules)/finance/incomes/': typeof mainmodulesFinanceIncomesIndexRoute
  '/(main)/(modules)/finance/projections/': typeof mainmodulesFinanceProjectionsIndexRoute
  '/(main)/(modules)/follow-ups/$id/': typeof mainmodulesFollowUpsIdIndexRoute
  '/(main)/(modules)/follow-ups/create/': typeof mainmodulesFollowUpsCreateIndexRoute
  '/(main)/(modules)/loans/$id/': typeof mainmodulesLoansIdIndexRoute
  '/(main)/(modules)/loans/create/': typeof mainmodulesLoansCreateIndexRoute
  '/(main)/(modules)/loans/purpouses/': typeof mainmodulesLoansPurpousesIndexRoute
  '/(main)/(modules)/profiles/$id/': typeof mainmodulesProfilesIdIndexRoute
  '/(main)/(modules)/profiles/create/': typeof mainmodulesProfilesCreateIndexRoute
  '/(main)/(modules)/projects/create/': typeof mainmodulesProjectsCreateIndexRoute
  '/(main)/(modules)/projects/settings/': typeof mainmodulesProjectsSettingsIndexRoute
  '/(main)/(modules)/reports/$id/': typeof mainmodulesReportsIdIndexRoute
  '/(main)/(modules)/reports/create/': typeof mainmodulesReportsCreateIndexRoute
  '/(main)/(modules)/reports/generate/': typeof mainmodulesReportsGenerateIndexRoute
  '/(main)/(modules)/transactions/$id/': typeof mainmodulesTransactionsIdIndexRoute
  '/(main)/(modules)/transactions/create/': typeof mainmodulesTransactionsCreateIndexRoute
  '/(main)/(modules)/transactions/periods/': typeof mainmodulesTransactionsPeriodsIndexRoute
  '/(main)/(modules)/access-control/roles/$id/': typeof mainmodulesAccessControlRolesIdIndexRoute
  '/(main)/(modules)/access-control/roles/create/': typeof mainmodulesAccessControlRolesCreateIndexRoute
  '/(main)/(modules)/access-control/users/$username/': typeof mainmodulesAccessControlUsersUsernameIndexRoute
  '/(main)/(modules)/access-control/users/create/': typeof mainmodulesAccessControlUsersCreateIndexRoute
  '/(main)/(modules)/collaterals/$id/edit/': typeof mainmodulesCollateralsIdEditIndexRoute
  '/(main)/(modules)/collaterals/$id/settings/': typeof mainmodulesCollateralsIdSettingsIndexRoute
  '/(main)/(modules)/follow-ups/$id/edit/': typeof mainmodulesFollowUpsIdEditIndexRoute
  '/(main)/(modules)/loans/$id/settings/': typeof mainmodulesLoansIdSettingsIndexRoute
  '/(main)/(modules)/loans/purpouses/create/': typeof mainmodulesLoansPurpousesCreateIndexRoute
  '/(main)/(modules)/profiles/$id/edit/': typeof mainmodulesProfilesIdEditIndexRoute
  '/(main)/(modules)/reports/$id/edit/': typeof mainmodulesReportsIdEditIndexRoute
  '/(main)/(modules)/transactions/periods/create/': typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  '/(main)/(modules)/transactions/receipt-report-template/create/': typeof mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute
  '/(main)/(modules)/access-control/roles/$id/edit/': typeof mainmodulesAccessControlRolesIdEditIndexRoute
  '/(main)/(modules)/access-control/users/$username/edit/': typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  '/(main)/(modules)/loans/purpouses/$id/edit/': typeof mainmodulesLoansPurpousesIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/logout/'
    | '/reset-password/'
    | '/access-control/'
    | '/account-statements/'
    | '/adjustment-notes/'
    | '/amortizations/'
    | '/collaterals/'
    | '/follow-ups/'
    | '/loans/'
    | '/profiles/'
    | '/reports/'
    | '/transactions/'
    | '/adjustment-notes/$id/'
    | '/adjustment-notes/create/'
    | '/collaterals/$id/'
    | '/collaterals/create/'
    | '/finance/expenses/'
    | '/finance/incomes/'
    | '/finance/projections/'
    | '/follow-ups/$id/'
    | '/follow-ups/create/'
    | '/loans/$id/'
    | '/loans/create/'
    | '/loans/purpouses/'
    | '/profiles/$id/'
    | '/profiles/create/'
    | '/projects/create/'
    | '/projects/settings/'
    | '/reports/$id/'
    | '/reports/create/'
    | '/reports/generate/'
    | '/transactions/$id/'
    | '/transactions/create/'
    | '/transactions/periods/'
    | '/access-control/roles/$id/'
    | '/access-control/roles/create/'
    | '/access-control/users/$username/'
    | '/access-control/users/create/'
    | '/collaterals/$id/edit/'
    | '/collaterals/$id/settings/'
    | '/follow-ups/$id/edit/'
    | '/loans/$id/settings/'
    | '/loans/purpouses/create/'
    | '/profiles/$id/edit/'
    | '/reports/$id/edit/'
    | '/transactions/periods/create/'
    | '/transactions/receipt-report-template/create/'
    | '/access-control/roles/$id/edit/'
    | '/access-control/users/$username/edit/'
    | '/loans/purpouses/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/access-control'
    | '/account-statements'
    | '/adjustment-notes'
    | '/amortizations'
    | '/collaterals'
    | '/follow-ups'
    | '/loans'
    | '/profiles'
    | '/reports'
    | '/transactions'
    | '/adjustment-notes/$id'
    | '/adjustment-notes/create'
    | '/collaterals/$id'
    | '/collaterals/create'
    | '/finance/expenses'
    | '/finance/incomes'
    | '/finance/projections'
    | '/follow-ups/$id'
    | '/follow-ups/create'
    | '/loans/$id'
    | '/loans/create'
    | '/loans/purpouses'
    | '/profiles/$id'
    | '/profiles/create'
    | '/projects/create'
    | '/projects/settings'
    | '/reports/$id'
    | '/reports/create'
    | '/reports/generate'
    | '/transactions/$id'
    | '/transactions/create'
    | '/transactions/periods'
    | '/access-control/roles/$id'
    | '/access-control/roles/create'
    | '/access-control/users/$username'
    | '/access-control/users/create'
    | '/collaterals/$id/edit'
    | '/collaterals/$id/settings'
    | '/follow-ups/$id/edit'
    | '/loans/$id/settings'
    | '/loans/purpouses/create'
    | '/profiles/$id/edit'
    | '/reports/$id/edit'
    | '/transactions/periods/create'
    | '/transactions/receipt-report-template/create'
    | '/access-control/roles/$id/edit'
    | '/access-control/users/$username/edit'
    | '/loans/purpouses/$id/edit'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/(modules)'
    | '/(main)/'
    | '/login/'
    | '/logout/'
    | '/(main)/reset-password/'
    | '/(main)/(modules)/access-control/'
    | '/(main)/(modules)/account-statements/'
    | '/(main)/(modules)/adjustment-notes/'
    | '/(main)/(modules)/amortizations/'
    | '/(main)/(modules)/collaterals/'
    | '/(main)/(modules)/follow-ups/'
    | '/(main)/(modules)/loans/'
    | '/(main)/(modules)/profiles/'
    | '/(main)/(modules)/reports/'
    | '/(main)/(modules)/transactions/'
    | '/(main)/(modules)/adjustment-notes/$id/'
    | '/(main)/(modules)/adjustment-notes/create/'
    | '/(main)/(modules)/collaterals/$id/'
    | '/(main)/(modules)/collaterals/create/'
    | '/(main)/(modules)/finance/expenses/'
    | '/(main)/(modules)/finance/incomes/'
    | '/(main)/(modules)/finance/projections/'
    | '/(main)/(modules)/follow-ups/$id/'
    | '/(main)/(modules)/follow-ups/create/'
    | '/(main)/(modules)/loans/$id/'
    | '/(main)/(modules)/loans/create/'
    | '/(main)/(modules)/loans/purpouses/'
    | '/(main)/(modules)/profiles/$id/'
    | '/(main)/(modules)/profiles/create/'
    | '/(main)/(modules)/projects/create/'
    | '/(main)/(modules)/projects/settings/'
    | '/(main)/(modules)/reports/$id/'
    | '/(main)/(modules)/reports/create/'
    | '/(main)/(modules)/reports/generate/'
    | '/(main)/(modules)/transactions/$id/'
    | '/(main)/(modules)/transactions/create/'
    | '/(main)/(modules)/transactions/periods/'
    | '/(main)/(modules)/access-control/roles/$id/'
    | '/(main)/(modules)/access-control/roles/create/'
    | '/(main)/(modules)/access-control/users/$username/'
    | '/(main)/(modules)/access-control/users/create/'
    | '/(main)/(modules)/collaterals/$id/edit/'
    | '/(main)/(modules)/collaterals/$id/settings/'
    | '/(main)/(modules)/follow-ups/$id/edit/'
    | '/(main)/(modules)/loans/$id/settings/'
    | '/(main)/(modules)/loans/purpouses/create/'
    | '/(main)/(modules)/profiles/$id/edit/'
    | '/(main)/(modules)/reports/$id/edit/'
    | '/(main)/(modules)/transactions/periods/create/'
    | '/(main)/(modules)/transactions/receipt-report-template/create/'
    | '/(main)/(modules)/access-control/roles/$id/edit/'
    | '/(main)/(modules)/access-control/users/$username/edit/'
    | '/(main)/(modules)/loans/purpouses/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(modules)': {
      id: '/(main)/(modules)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainmodulesRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/reset-password/': {
      id: '/(main)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof mainResetPasswordIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(modules)/transactions/': {
      id: '/(main)/(modules)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof mainmodulesTransactionsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/reports/': {
      id: '/(main)/(modules)/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof mainmodulesReportsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/': {
      id: '/(main)/(modules)/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof mainmodulesProfilesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/': {
      id: '/(main)/(modules)/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof mainmodulesLoansIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/': {
      id: '/(main)/(modules)/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof mainmodulesFollowUpsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/': {
      id: '/(main)/(modules)/collaterals/'
      path: '/collaterals'
      fullPath: '/collaterals/'
      preLoaderRoute: typeof mainmodulesCollateralsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/amortizations/': {
      id: '/(main)/(modules)/amortizations/'
      path: '/amortizations'
      fullPath: '/amortizations/'
      preLoaderRoute: typeof mainmodulesAmortizationsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/': {
      id: '/(main)/(modules)/adjustment-notes/'
      path: '/adjustment-notes'
      fullPath: '/adjustment-notes/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/account-statements/': {
      id: '/(main)/(modules)/account-statements/'
      path: '/account-statements'
      fullPath: '/account-statements/'
      preLoaderRoute: typeof mainmodulesAccountStatementsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/': {
      id: '/(main)/(modules)/access-control/'
      path: '/access-control'
      fullPath: '/access-control/'
      preLoaderRoute: typeof mainmodulesAccessControlIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/periods/': {
      id: '/(main)/(modules)/transactions/periods/'
      path: '/transactions/periods'
      fullPath: '/transactions/periods/'
      preLoaderRoute: typeof mainmodulesTransactionsPeriodsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/create/': {
      id: '/(main)/(modules)/transactions/create/'
      path: '/transactions/create'
      fullPath: '/transactions/create/'
      preLoaderRoute: typeof mainmodulesTransactionsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/$id/': {
      id: '/(main)/(modules)/transactions/$id/'
      path: '/transactions/$id'
      fullPath: '/transactions/$id/'
      preLoaderRoute: typeof mainmodulesTransactionsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/reports/generate/': {
      id: '/(main)/(modules)/reports/generate/'
      path: '/reports/generate'
      fullPath: '/reports/generate/'
      preLoaderRoute: typeof mainmodulesReportsGenerateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/reports/create/': {
      id: '/(main)/(modules)/reports/create/'
      path: '/reports/create'
      fullPath: '/reports/create/'
      preLoaderRoute: typeof mainmodulesReportsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/reports/$id/': {
      id: '/(main)/(modules)/reports/$id/'
      path: '/reports/$id'
      fullPath: '/reports/$id/'
      preLoaderRoute: typeof mainmodulesReportsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/projects/settings/': {
      id: '/(main)/(modules)/projects/settings/'
      path: '/projects/settings'
      fullPath: '/projects/settings/'
      preLoaderRoute: typeof mainmodulesProjectsSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/projects/create/': {
      id: '/(main)/(modules)/projects/create/'
      path: '/projects/create'
      fullPath: '/projects/create/'
      preLoaderRoute: typeof mainmodulesProjectsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/create/': {
      id: '/(main)/(modules)/profiles/create/'
      path: '/profiles/create'
      fullPath: '/profiles/create/'
      preLoaderRoute: typeof mainmodulesProfilesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/': {
      id: '/(main)/(modules)/profiles/$id/'
      path: '/profiles/$id'
      fullPath: '/profiles/$id/'
      preLoaderRoute: typeof mainmodulesProfilesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purpouses/': {
      id: '/(main)/(modules)/loans/purpouses/'
      path: '/loans/purpouses'
      fullPath: '/loans/purpouses/'
      preLoaderRoute: typeof mainmodulesLoansPurpousesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/create/': {
      id: '/(main)/(modules)/loans/create/'
      path: '/loans/create'
      fullPath: '/loans/create/'
      preLoaderRoute: typeof mainmodulesLoansCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/': {
      id: '/(main)/(modules)/loans/$id/'
      path: '/loans/$id'
      fullPath: '/loans/$id/'
      preLoaderRoute: typeof mainmodulesLoansIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/create/': {
      id: '/(main)/(modules)/follow-ups/create/'
      path: '/follow-ups/create'
      fullPath: '/follow-ups/create/'
      preLoaderRoute: typeof mainmodulesFollowUpsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/$id/': {
      id: '/(main)/(modules)/follow-ups/$id/'
      path: '/follow-ups/$id'
      fullPath: '/follow-ups/$id/'
      preLoaderRoute: typeof mainmodulesFollowUpsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/projections/': {
      id: '/(main)/(modules)/finance/projections/'
      path: '/finance/projections'
      fullPath: '/finance/projections/'
      preLoaderRoute: typeof mainmodulesFinanceProjectionsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/incomes/': {
      id: '/(main)/(modules)/finance/incomes/'
      path: '/finance/incomes'
      fullPath: '/finance/incomes/'
      preLoaderRoute: typeof mainmodulesFinanceIncomesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/finance/expenses/': {
      id: '/(main)/(modules)/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/finance/expenses/'
      preLoaderRoute: typeof mainmodulesFinanceExpensesIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/create/': {
      id: '/(main)/(modules)/collaterals/create/'
      path: '/collaterals/create'
      fullPath: '/collaterals/create/'
      preLoaderRoute: typeof mainmodulesCollateralsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/': {
      id: '/(main)/(modules)/collaterals/$id/'
      path: '/collaterals/$id'
      fullPath: '/collaterals/$id/'
      preLoaderRoute: typeof mainmodulesCollateralsIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/create/': {
      id: '/(main)/(modules)/adjustment-notes/create/'
      path: '/adjustment-notes/create'
      fullPath: '/adjustment-notes/create/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/adjustment-notes/$id/': {
      id: '/(main)/(modules)/adjustment-notes/$id/'
      path: '/adjustment-notes/$id'
      fullPath: '/adjustment-notes/$id/'
      preLoaderRoute: typeof mainmodulesAdjustmentNotesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/receipt-report-template/create/': {
      id: '/(main)/(modules)/transactions/receipt-report-template/create/'
      path: '/transactions/receipt-report-template/create'
      fullPath: '/transactions/receipt-report-template/create/'
      preLoaderRoute: typeof mainmodulesTransactionsReceiptReportTemplateCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/transactions/periods/create/': {
      id: '/(main)/(modules)/transactions/periods/create/'
      path: '/transactions/periods/create'
      fullPath: '/transactions/periods/create/'
      preLoaderRoute: typeof mainmodulesTransactionsPeriodsCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/reports/$id/edit/': {
      id: '/(main)/(modules)/reports/$id/edit/'
      path: '/reports/$id/edit'
      fullPath: '/reports/$id/edit/'
      preLoaderRoute: typeof mainmodulesReportsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/profiles/$id/edit/': {
      id: '/(main)/(modules)/profiles/$id/edit/'
      path: '/profiles/$id/edit'
      fullPath: '/profiles/$id/edit/'
      preLoaderRoute: typeof mainmodulesProfilesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purpouses/create/': {
      id: '/(main)/(modules)/loans/purpouses/create/'
      path: '/loans/purpouses/create'
      fullPath: '/loans/purpouses/create/'
      preLoaderRoute: typeof mainmodulesLoansPurpousesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/$id/settings/': {
      id: '/(main)/(modules)/loans/$id/settings/'
      path: '/loans/$id/settings'
      fullPath: '/loans/$id/settings/'
      preLoaderRoute: typeof mainmodulesLoansIdSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/follow-ups/$id/edit/': {
      id: '/(main)/(modules)/follow-ups/$id/edit/'
      path: '/follow-ups/$id/edit'
      fullPath: '/follow-ups/$id/edit/'
      preLoaderRoute: typeof mainmodulesFollowUpsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/settings/': {
      id: '/(main)/(modules)/collaterals/$id/settings/'
      path: '/collaterals/$id/settings'
      fullPath: '/collaterals/$id/settings/'
      preLoaderRoute: typeof mainmodulesCollateralsIdSettingsIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/collaterals/$id/edit/': {
      id: '/(main)/(modules)/collaterals/$id/edit/'
      path: '/collaterals/$id/edit'
      fullPath: '/collaterals/$id/edit/'
      preLoaderRoute: typeof mainmodulesCollateralsIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/create/': {
      id: '/(main)/(modules)/access-control/users/create/'
      path: '/access-control/users/create'
      fullPath: '/access-control/users/create/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/$username/': {
      id: '/(main)/(modules)/access-control/users/$username/'
      path: '/access-control/users/$username'
      fullPath: '/access-control/users/$username/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersUsernameIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/create/': {
      id: '/(main)/(modules)/access-control/roles/create/'
      path: '/access-control/roles/create'
      fullPath: '/access-control/roles/create/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesCreateIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/': {
      id: '/(main)/(modules)/access-control/roles/$id/'
      path: '/access-control/roles/$id'
      fullPath: '/access-control/roles/$id/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/loans/purpouses/$id/edit/': {
      id: '/(main)/(modules)/loans/purpouses/$id/edit/'
      path: '/loans/purpouses/$id/edit'
      fullPath: '/loans/purpouses/$id/edit/'
      preLoaderRoute: typeof mainmodulesLoansPurpousesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/users/$username/edit/': {
      id: '/(main)/(modules)/access-control/users/$username/edit/'
      path: '/access-control/users/$username/edit'
      fullPath: '/access-control/users/$username/edit/'
      preLoaderRoute: typeof mainmodulesAccessControlUsersUsernameEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
    '/(main)/(modules)/access-control/roles/$id/edit/': {
      id: '/(main)/(modules)/access-control/roles/$id/edit/'
      path: '/access-control/roles/$id/edit'
      fullPath: '/access-control/roles/$id/edit/'
      preLoaderRoute: typeof mainmodulesAccessControlRolesIdEditIndexRouteImport
      parentRoute: typeof mainmodulesRouteRoute
    }
  }
}

interface mainmodulesRouteRouteChildren {
  mainmodulesAccessControlIndexRoute: typeof mainmodulesAccessControlIndexRoute
  mainmodulesAccountStatementsIndexRoute: typeof mainmodulesAccountStatementsIndexRoute
  mainmodulesAdjustmentNotesIndexRoute: typeof mainmodulesAdjustmentNotesIndexRoute
  mainmodulesAmortizationsIndexRoute: typeof mainmodulesAmortizationsIndexRoute
  mainmodulesCollateralsIndexRoute: typeof mainmodulesCollateralsIndexRoute
  mainmodulesFollowUpsIndexRoute: typeof mainmodulesFollowUpsIndexRoute
  mainmodulesLoansIndexRoute: typeof mainmodulesLoansIndexRoute
  mainmodulesProfilesIndexRoute: typeof mainmodulesProfilesIndexRoute
  mainmodulesReportsIndexRoute: typeof mainmodulesReportsIndexRoute
  mainmodulesTransactionsIndexRoute: typeof mainmodulesTransactionsIndexRoute
  mainmodulesAdjustmentNotesIdIndexRoute: typeof mainmodulesAdjustmentNotesIdIndexRoute
  mainmodulesAdjustmentNotesCreateIndexRoute: typeof mainmodulesAdjustmentNotesCreateIndexRoute
  mainmodulesCollateralsIdIndexRoute: typeof mainmodulesCollateralsIdIndexRoute
  mainmodulesCollateralsCreateIndexRoute: typeof mainmodulesCollateralsCreateIndexRoute
  mainmodulesFinanceExpensesIndexRoute: typeof mainmodulesFinanceExpensesIndexRoute
  mainmodulesFinanceIncomesIndexRoute: typeof mainmodulesFinanceIncomesIndexRoute
  mainmodulesFinanceProjectionsIndexRoute: typeof mainmodulesFinanceProjectionsIndexRoute
  mainmodulesFollowUpsIdIndexRoute: typeof mainmodulesFollowUpsIdIndexRoute
  mainmodulesFollowUpsCreateIndexRoute: typeof mainmodulesFollowUpsCreateIndexRoute
  mainmodulesLoansIdIndexRoute: typeof mainmodulesLoansIdIndexRoute
  mainmodulesLoansCreateIndexRoute: typeof mainmodulesLoansCreateIndexRoute
  mainmodulesLoansPurpousesIndexRoute: typeof mainmodulesLoansPurpousesIndexRoute
  mainmodulesProfilesIdIndexRoute: typeof mainmodulesProfilesIdIndexRoute
  mainmodulesProfilesCreateIndexRoute: typeof mainmodulesProfilesCreateIndexRoute
  mainmodulesProjectsCreateIndexRoute: typeof mainmodulesProjectsCreateIndexRoute
  mainmodulesProjectsSettingsIndexRoute: typeof mainmodulesProjectsSettingsIndexRoute
  mainmodulesReportsIdIndexRoute: typeof mainmodulesReportsIdIndexRoute
  mainmodulesReportsCreateIndexRoute: typeof mainmodulesReportsCreateIndexRoute
  mainmodulesReportsGenerateIndexRoute: typeof mainmodulesReportsGenerateIndexRoute
  mainmodulesTransactionsIdIndexRoute: typeof mainmodulesTransactionsIdIndexRoute
  mainmodulesTransactionsCreateIndexRoute: typeof mainmodulesTransactionsCreateIndexRoute
  mainmodulesTransactionsPeriodsIndexRoute: typeof mainmodulesTransactionsPeriodsIndexRoute
  mainmodulesAccessControlRolesIdIndexRoute: typeof mainmodulesAccessControlRolesIdIndexRoute
  mainmodulesAccessControlRolesCreateIndexRoute: typeof mainmodulesAccessControlRolesCreateIndexRoute
  mainmodulesAccessControlUsersUsernameIndexRoute: typeof mainmodulesAccessControlUsersUsernameIndexRoute
  mainmodulesAccessControlUsersCreateIndexRoute: typeof mainmodulesAccessControlUsersCreateIndexRoute
  mainmodulesCollateralsIdEditIndexRoute: typeof mainmodulesCollateralsIdEditIndexRoute
  mainmodulesCollateralsIdSettingsIndexRoute: typeof mainmodulesCollateralsIdSettingsIndexRoute
  mainmodulesFollowUpsIdEditIndexRoute: typeof mainmodulesFollowUpsIdEditIndexRoute
  mainmodulesLoansIdSettingsIndexRoute: typeof mainmodulesLoansIdSettingsIndexRoute
  mainmodulesLoansPurpousesCreateIndexRoute: typeof mainmodulesLoansPurpousesCreateIndexRoute
  mainmodulesProfilesIdEditIndexRoute: typeof mainmodulesProfilesIdEditIndexRoute
  mainmodulesReportsIdEditIndexRoute: typeof mainmodulesReportsIdEditIndexRoute
  mainmodulesTransactionsPeriodsCreateIndexRoute: typeof mainmodulesTransactionsPeriodsCreateIndexRoute
  mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute: typeof mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute
  mainmodulesAccessControlRolesIdEditIndexRoute: typeof mainmodulesAccessControlRolesIdEditIndexRoute
  mainmodulesAccessControlUsersUsernameEditIndexRoute: typeof mainmodulesAccessControlUsersUsernameEditIndexRoute
  mainmodulesLoansPurpousesIdEditIndexRoute: typeof mainmodulesLoansPurpousesIdEditIndexRoute
}

const mainmodulesRouteRouteChildren: mainmodulesRouteRouteChildren = {
  mainmodulesAccessControlIndexRoute: mainmodulesAccessControlIndexRoute,
  mainmodulesAccountStatementsIndexRoute:
    mainmodulesAccountStatementsIndexRoute,
  mainmodulesAdjustmentNotesIndexRoute: mainmodulesAdjustmentNotesIndexRoute,
  mainmodulesAmortizationsIndexRoute: mainmodulesAmortizationsIndexRoute,
  mainmodulesCollateralsIndexRoute: mainmodulesCollateralsIndexRoute,
  mainmodulesFollowUpsIndexRoute: mainmodulesFollowUpsIndexRoute,
  mainmodulesLoansIndexRoute: mainmodulesLoansIndexRoute,
  mainmodulesProfilesIndexRoute: mainmodulesProfilesIndexRoute,
  mainmodulesReportsIndexRoute: mainmodulesReportsIndexRoute,
  mainmodulesTransactionsIndexRoute: mainmodulesTransactionsIndexRoute,
  mainmodulesAdjustmentNotesIdIndexRoute:
    mainmodulesAdjustmentNotesIdIndexRoute,
  mainmodulesAdjustmentNotesCreateIndexRoute:
    mainmodulesAdjustmentNotesCreateIndexRoute,
  mainmodulesCollateralsIdIndexRoute: mainmodulesCollateralsIdIndexRoute,
  mainmodulesCollateralsCreateIndexRoute:
    mainmodulesCollateralsCreateIndexRoute,
  mainmodulesFinanceExpensesIndexRoute: mainmodulesFinanceExpensesIndexRoute,
  mainmodulesFinanceIncomesIndexRoute: mainmodulesFinanceIncomesIndexRoute,
  mainmodulesFinanceProjectionsIndexRoute:
    mainmodulesFinanceProjectionsIndexRoute,
  mainmodulesFollowUpsIdIndexRoute: mainmodulesFollowUpsIdIndexRoute,
  mainmodulesFollowUpsCreateIndexRoute: mainmodulesFollowUpsCreateIndexRoute,
  mainmodulesLoansIdIndexRoute: mainmodulesLoansIdIndexRoute,
  mainmodulesLoansCreateIndexRoute: mainmodulesLoansCreateIndexRoute,
  mainmodulesLoansPurpousesIndexRoute: mainmodulesLoansPurpousesIndexRoute,
  mainmodulesProfilesIdIndexRoute: mainmodulesProfilesIdIndexRoute,
  mainmodulesProfilesCreateIndexRoute: mainmodulesProfilesCreateIndexRoute,
  mainmodulesProjectsCreateIndexRoute: mainmodulesProjectsCreateIndexRoute,
  mainmodulesProjectsSettingsIndexRoute: mainmodulesProjectsSettingsIndexRoute,
  mainmodulesReportsIdIndexRoute: mainmodulesReportsIdIndexRoute,
  mainmodulesReportsCreateIndexRoute: mainmodulesReportsCreateIndexRoute,
  mainmodulesReportsGenerateIndexRoute: mainmodulesReportsGenerateIndexRoute,
  mainmodulesTransactionsIdIndexRoute: mainmodulesTransactionsIdIndexRoute,
  mainmodulesTransactionsCreateIndexRoute:
    mainmodulesTransactionsCreateIndexRoute,
  mainmodulesTransactionsPeriodsIndexRoute:
    mainmodulesTransactionsPeriodsIndexRoute,
  mainmodulesAccessControlRolesIdIndexRoute:
    mainmodulesAccessControlRolesIdIndexRoute,
  mainmodulesAccessControlRolesCreateIndexRoute:
    mainmodulesAccessControlRolesCreateIndexRoute,
  mainmodulesAccessControlUsersUsernameIndexRoute:
    mainmodulesAccessControlUsersUsernameIndexRoute,
  mainmodulesAccessControlUsersCreateIndexRoute:
    mainmodulesAccessControlUsersCreateIndexRoute,
  mainmodulesCollateralsIdEditIndexRoute:
    mainmodulesCollateralsIdEditIndexRoute,
  mainmodulesCollateralsIdSettingsIndexRoute:
    mainmodulesCollateralsIdSettingsIndexRoute,
  mainmodulesFollowUpsIdEditIndexRoute: mainmodulesFollowUpsIdEditIndexRoute,
  mainmodulesLoansIdSettingsIndexRoute: mainmodulesLoansIdSettingsIndexRoute,
  mainmodulesLoansPurpousesCreateIndexRoute:
    mainmodulesLoansPurpousesCreateIndexRoute,
  mainmodulesProfilesIdEditIndexRoute: mainmodulesProfilesIdEditIndexRoute,
  mainmodulesReportsIdEditIndexRoute: mainmodulesReportsIdEditIndexRoute,
  mainmodulesTransactionsPeriodsCreateIndexRoute:
    mainmodulesTransactionsPeriodsCreateIndexRoute,
  mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute:
    mainmodulesTransactionsReceiptReportTemplateCreateIndexRoute,
  mainmodulesAccessControlRolesIdEditIndexRoute:
    mainmodulesAccessControlRolesIdEditIndexRoute,
  mainmodulesAccessControlUsersUsernameEditIndexRoute:
    mainmodulesAccessControlUsersUsernameEditIndexRoute,
  mainmodulesLoansPurpousesIdEditIndexRoute:
    mainmodulesLoansPurpousesIdEditIndexRoute,
}

const mainmodulesRouteRouteWithChildren =
  mainmodulesRouteRoute._addFileChildren(mainmodulesRouteRouteChildren)

interface mainRouteRouteChildren {
  mainmodulesRouteRoute: typeof mainmodulesRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
  mainResetPasswordIndexRoute: typeof mainResetPasswordIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainmodulesRouteRoute: mainmodulesRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
  mainResetPasswordIndexRoute: mainResetPasswordIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
