/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as modulesRouteRouteImport } from './routes/(modules)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as modulesIndexRouteImport } from './routes/(modules)/index'
import { Route as modulesAccessControlRouteRouteImport } from './routes/(modules)/access-control/route'
import { Route as modulesAccessControlIndexRouteImport } from './routes/(modules)/access-control/index'

const modulesRouteRoute = modulesRouteRouteImport.update({
  id: '/(modules)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const modulesIndexRoute = modulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => modulesRouteRoute,
} as any)
const modulesAccessControlRouteRoute =
  modulesAccessControlRouteRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => modulesRouteRoute,
  } as any)
const modulesAccessControlIndexRoute =
  modulesAccessControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => modulesAccessControlRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/access-control': typeof modulesAccessControlRouteRouteWithChildren
  '/': typeof modulesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/access-control/': typeof modulesAccessControlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesIndexRoute
  '/login': typeof LoginIndexRoute
  '/access-control': typeof modulesAccessControlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(modules)': typeof modulesRouteRouteWithChildren
  '/(modules)/access-control': typeof modulesAccessControlRouteRouteWithChildren
  '/(modules)/': typeof modulesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(modules)/access-control/': typeof modulesAccessControlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/access-control' | '/' | '/login/' | '/access-control/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/access-control'
  id:
    | '__root__'
    | '/(modules)'
    | '/(modules)/access-control'
    | '/(modules)/'
    | '/login/'
    | '/(modules)/access-control/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesRouteRoute: typeof modulesRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(modules)': {
      id: '/(modules)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof modulesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(modules)/': {
      id: '/(modules)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesIndexRouteImport
      parentRoute: typeof modulesRouteRoute
    }
    '/(modules)/access-control': {
      id: '/(modules)/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof modulesAccessControlRouteRouteImport
      parentRoute: typeof modulesRouteRoute
    }
    '/(modules)/access-control/': {
      id: '/(modules)/access-control/'
      path: '/'
      fullPath: '/access-control/'
      preLoaderRoute: typeof modulesAccessControlIndexRouteImport
      parentRoute: typeof modulesAccessControlRouteRoute
    }
  }
}

interface modulesAccessControlRouteRouteChildren {
  modulesAccessControlIndexRoute: typeof modulesAccessControlIndexRoute
}

const modulesAccessControlRouteRouteChildren: modulesAccessControlRouteRouteChildren =
  {
    modulesAccessControlIndexRoute: modulesAccessControlIndexRoute,
  }

const modulesAccessControlRouteRouteWithChildren =
  modulesAccessControlRouteRoute._addFileChildren(
    modulesAccessControlRouteRouteChildren,
  )

interface modulesRouteRouteChildren {
  modulesAccessControlRouteRoute: typeof modulesAccessControlRouteRouteWithChildren
  modulesIndexRoute: typeof modulesIndexRoute
}

const modulesRouteRouteChildren: modulesRouteRouteChildren = {
  modulesAccessControlRouteRoute: modulesAccessControlRouteRouteWithChildren,
  modulesIndexRoute: modulesIndexRoute,
}

const modulesRouteRouteWithChildren = modulesRouteRoute._addFileChildren(
  modulesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  modulesRouteRoute: modulesRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
